// plan-wise-react-php/frontend/src/pages/Categories.tsx
import React, { useState, useEffect } from 'react';
import category from '../services/category-service';
import './Categories.css';

function Categories() {
  const [categories, setCategories] = useState([]);
  const [newCategory, setNewCategory] = useState("");
  const [showInput, setShowInput] = useState(false);

  useEffect(() => {
    fetchCategories();
  }, []);

  async function fetchCategories() {
    try {
      let response = await category.getAll();
      setCategories(response.category || []);
    } catch(exception){
      console.log(exception);
    }
  }

  async function createCategory() {
    if (newCategory) {
      let body = {
        category_name: newCategory
      };
      try {
        let response = await category.create(body);
        if (response.success) {
          setCategories([...categories, {
            id: response.category.id,
            category_name: newCategory,
            average_monthly_expense: 0
          }]);
          setNewCategory("");
        } else {
          console.error(response.message);
        }
      } catch (exception) {
        console.error(exception);
      }
    } else {
      console.warn("Please enter a category name");
    }
  }

  async function updateCategory(index){
    await category.update(categories[index].id, {
      category_name: categories[index].category_name
    });
  }

  async function deleteCategory(index){
    let response = await category.delete(categories[index].id);
    if(response.success){
      setCategories(categories.filter((_, i) => i !== index));
    }
  }

  return (
    <div className="uui-page-padding">
      <div className="uui-container-large">
        <div className="uui-padding-vertical-xhuge">
          <div className="uui-text-align-center">
            <div className="uui-max-width-large align-center">
              <h2 className="uui-heading-medium">Categories</h2>
              <div className="uui-space-xsmall"></div>
              <div className="uui-text-size-large">Add and manage your expense <strong>categories</strong></div>
              <button className="button w-button" onClick={() => setShowInput(!showInput)}>+</button>
            </div>
          </div>
          <div className="uui-table">
            <div className="uui-table_heading-row">
              <div className="uui-table_heading-row-text">Category Name</div>
              <div className="uui-table_heading-row-text">Monthly Average</div>
              <div className="uui-table_heading-row-text">Action</div>
            </div>
            {showInput && 
              <input 
                id="new-category" 
                value={newCategory}
                onChange={(e) => setNewCategory(e.target.value)}
                type="text" 
                className="w-layout-grid uui-table_row new-row uui-table_feature uui-pricing07_row-lead-text w-100"
                onKeyPress={(e) => e.key === 'Enter' && createCategory()}
              />
            }
            {categories.map((category, index) => (
              <div key={category.id} className={`w-layout-grid uui-table_row ${index % 2 === 1 ? "background-color-gray50" : ""}`}>
                <div className="uui-table_feature">
                  <div className="uui-pricing07_row-lead-text">                                
                    <input type="text" className="expense-input" value={category.category_name} onChange={(e) => {
                      const newCategories = [...categories];
                      newCategories[index].category_name = e.target.value;
                      setCategories(newCategories);
                    }}/>
                  </div>
                </div>
                <div className="uui-table_row">
                  <div className="uui-pricing07_row-lead-text">   
                    ${category.average_monthly_expense.toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </div>
                </div>
                <div className="uui-table_row">
                  <div className="action">
                    <button type="button" className="btn btn-warning" onClick={() => updateCategory(index)}>Save</button>
                    <button type="button" className="btn btn-danger" onClick={() => deleteCategory(index)}>Delete</button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export default Categories;

// plan-wise-vue-python/frontend/src/pages/Categories.vue
<template>
    <div class="uui-page-padding">
        <div class="uui-container-large">
        <div class="uui-padding-vertical-xhuge">
            <div class="uui-text-align-center">
            <div class="uui-max-width-large align-center">
                <h2 class="uui-heading-medium">Categories</h2>
                <div class="uui-space-xsmall"></div>
                <div class="uui-text-size-large">Add and manage your expense <strong>categories</strong>
                <strong></strong>
                </div>
                <button class="button w-button" @click="inputToggle">+</button>
            </div>
            </div>
            <div class="uui-table">
                <div class="uui-table_heading-row">
                    <div class="uui-table_heading-row-text">Category Name</div>
                    <div class="uui-table_heading-row-text">Monthly Average</div>
                    <div class="uui-table_heading-row-text">Action</div>
                </div>
                <input 
                    v-if="showInput" 
                    id="new-category" 
                    v-model="newCategory" 
                    type="text" 
                    class="w-layout-grid uui-table_row new-row uui-table_feature uui-pricing07_row-lead-text w-100"
                    v-on:keyup.enter="createCategory"
                >
                <li v-for="(category, index) in categories" :key="category.id" :class="getClass(index)">
                    <div class="w-layout-grid uui-table_row" :class="getClass(index)">
                        <div class="uui-table_feature">
                            <div class="uui-pricing07_row-lead-text">                                
                                <input type="text" class="expense-input" v-model="categories[index].category_name">
                            </div>
                        </div>
                        <div class="uui-table_row">
                            <div class="uui-pricing07_row-lead-text">   
                                ${{ category.average_monthly_expense.toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 }) }}
                            </div>
                        </div>
                        <div class="uui-table_row">
                            <div class="action">
                                <button type="button" class="btn btn-warning" @click="updateCategory(index)">Save</button>
                                <button type="button" class="btn btn-danger" @click="deleteCategory(index)">Delete</button>
                            </div>
                        </div>
                    </div>
                </li>
            </div>
        </div>
        </div>
    </div>
</template>
  
<script>
import category from '../services/category-service';
export default {
    data() {
        return {
            categories: [],
            newCategory: "",
            showInput: false
        }
    },
    mounted() {
        document.title = "Plan Wise - Categories";
        this.fetchCategories();
    },
    methods: {
        async fetchCategories() {
            try {
                let response = await category.getAll();
                this.categories = response.category || [];
            } catch(exception){
                console.log(exception);
            }
        },
        async createCategory() {
            if (this.newCategory) {
                let body = {
                    category_name: this.newCategory
                };
                try {
                    let response = await category.create(body);
                    if (response.success) {
                        this.categories.push({
                            id: response.category.id,
                            category_name: this.newCategory,
                            average_monthly_expense: 0
                        });
                        this.newCategory = "";
                    } else {
                        console.error(response.message);
                    }
                } catch (exception) {
                    console.error(exception);
                }
            } else {
                console.warn("Please enter a category name");
            }
        },
        async inputToggle(){
            this.showInput = !this.showInput;
        },
        async updateCategory(index){
            await category.update(this.categories[index].id, {
                category_name: this.categories[index].category_name
            })
        },
        async deleteCategory(index){
            let response = await category.delete(this.categories[index].id)
            if(response.success){
                this.categories.splice(index, 1);
            }
        }
    },
    computed: {
        getClass(index) {
            return (index) => {
                return {
                    "background-color-gray50": index % 2 === 1,
                    "no-bullet": true
                }
            }
        }
    }
} 
</script>
  
<style scoped>
@import '../assets/components.css';
@import '../assets/budgeting-app.css';
.no-bullet {
    list-style: none;
}
.expense-input{
  width: 100%;
  padding: 5px;
  border-radius: 5px;
  border: 1px solid rgba(0, 0, 0, .1);
  background: transparent;
  font-family: system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Noto Sans,Ubuntu,Cantarell,Helvetica Neue,Oxygen,Fira Sans,Droid Sans,sans-serif;
    font-size: 1.125rem;
}
.action{
  display: flex;
  flex-direction: row;
  column-gap: 10px;
}
</style>
