// frontend/src/components/ConfirmationModal.vue
<template>
    <div class="modal fade" id="confirmationModal" ref="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="confirmationModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="confirmationModalLabel">{{ localHeaderMessage }}</h5>
            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {{ localBodyMessage }}
            <div class="alert alert-danger" v-if="displayErrorMessage" role="alert">
                Error occurred in this operation! Please try again
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            <button type="button" class="btn" :class="actionClass" @click="confimationAction">{{ actionMessage }}</button>
          </div>
        </div>
      </div>
    </div>
</template>
<style scoped>
@import '../assets/components.css';
@import '../assets/budgeting-app.css';

</style>
<script>
export default {
    props: [
        'headerMessage',
        'confimationAction',
        'actionMessage',
        'actionClass',
        'bodyMessage'
    ],
    data() {
        return {
            localHeaderMessage: '',
            localBodyMessage: '',
            displayErrorMessage: false
        };
    },
    mounted() {
        this.onShow();
    },
    methods: {
        onShow(){
            this.localHeaderMessage = this.headerMesage;
            this.localBodyMessage = this.bodyMessage;
        },
        showErrorMessage(){
            this.displayErrorMessage = true;
        },
        changeModalMessage(){

        }
    }
};
</script>

// plan-wise-angular-java/frontend/src/app/components/confirmation-modal/confirmation-modal.component.ts
import { Component, Input, OnInit, ViewChild, ElementRef } from '@angular/core';
import * as bootstrap from 'bootstrap';

@Component({
  selector: 'app-confirmation-modal',
  templateUrl: './confirmation-modal.component.html',
  styleUrls: ['./confirmation-modal.component.css', '../../../assets/components.css', '../../../assets/budgeting-app.css']
})

export class ConfirmationModalComponent implements OnInit {
  @Input() headerMessage = '';
  @Input() confirmationAction: () => void = () => { this.callback(this.index); };
  @Input() actionMessage = '';
  @Input() actionClass = '';
  @Input() bodyMessage = '';
  @ViewChild('confirmationModal') confirmationModal!: ElementRef;
  displayErrorMessage = false;
  callback: any;
  index: any;
  modalInstance: any;

  ngOnInit(): void {}

  open() {
    this.modalInstance = new bootstrap.Modal(this.confirmationModal.nativeElement);
    this.modalInstance.show();
  }

  close() {
    this.modalInstance.hide();
  }

  showErrorMessage() {
    this.displayErrorMessage = true;
  }

  changeModalMessage(newHeaderMessage: string, newBodyMessage: string, newActionMessage: string, callback: any, index: any) {
    this.actionMessage = newActionMessage;
    this.headerMessage = newHeaderMessage;
    this.bodyMessage = newBodyMessage;
    console.log(newHeaderMessage.split(" ")[0])
    this.actionClass = newHeaderMessage.split(" ")[0] === "Delete"? "btn btn-danger" : "";
    this.callback = callback;
    this.index = index;
  }  
}

<div #confirmationModal class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="confirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="confirmationModalLabel">{{ headerMessage }}</h5>
          <button type="button" class="close" aria-label="Close" (click)="close()">
            <span aria-hidden="true">x</span>
          </button>
        </div>
        <div class="modal-body">
          {{ bodyMessage }}
          <div *ngIf="displayErrorMessage" class="alert alert-danger" role="alert">
            Error occurred in this operation! Please try again
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" (click)="close()">Cancel</button>
          <button type="button" [ngClass]="actionClass" (click)="confirmationAction()">{{ actionMessage }}</button>
        </div>
      </div>
    </div>
</div>
