// plan-wise-angular-java/frontend/src/app/pages/categories/categories.component.ts
import { Component, OnInit } from '@angular/core';
import { CategoryService } from '../../../services/category.service';

@Component({
  selector: 'app-categories',
  templateUrl: './categories.component.html',
  styleUrls: ['./categories.component.css', '../../../assets/components.css', '../../../assets/budgeting-app.css']
})
export class CategoriesComponent implements OnInit {
  categories: any = [];
  newCategory = '';
  showInput = false;

  constructor(private categoryService: CategoryService) {}

  ngOnInit(): void {
    this.fetchCategories();
  }

  async fetchCategories() {
    try {
      let response: any = await this.categoryService.getAll();
      this.categories = response.categories || [];
    } catch(exception){
      console.log(exception);
    }
  }

  async createCategory() {
    if (this.newCategory) {
      let body = {
        categoryName: this.newCategory
      };
      try {
        let response: any = await this.categoryService.create(body);
        if (response.success) {
          this.categories.push({
            id: response.category.id,
            category_name: this.newCategory,
            average_monthly_expense: 0
          });
          this.newCategory = '';
        } else {
          console.error(response.message);
        }
      } catch (exception) {
        console.error(exception);
      }
    } else {
      console.warn("Please enter a category name");
    }
  }

  async updateCategory(index: number){
    await this.categoryService.update(this.categories[index].id, {
      categoryName: this.categories[index].category_name
    });
  }

  async deleteCategory(index: number){
    let response: any = await this.categoryService.delete(this.categories[index].id);
    if(response.success){
      this.categories = this.categories.filter((_: any, i: number) => i !== index);
    }
  }
}

<div class="uui-page-padding">
    <div class="uui-container-large">
      <div class="uui-padding-vertical-xhuge">
        <div class="uui-text-align-center">
          <div class="uui-max-width-large align-center">
            <h2 class="uui-heading-medium">Categories</h2>
            <div class="uui-space-xsmall"></div>
            <div class="uui-text-size-large">Add and manage your expense <strong>categories</strong></div>
            <button class="button w-button" (click)="showInput = !showInput">+</button>
          </div>
        </div>
        <div class="uui-table">
          <div class="uui-table_heading-row">
            <div class="uui-table_heading-row-text">Category Name</div>
            <div class="uui-table_heading-row-text">Monthly Average</div>
            <div class="uui-table_heading-row-text">Action</div>
          </div>
          <input 
            *ngIf="showInput"
            id="new-category" 
            [(ngModel)]="newCategory"
            type="text" 
            class="w-layout-grid uui-table_row new-row uui-table_feature uui-pricing07_row-lead-text w-100"
            (keyup.enter)="createCategory()"
          />
          <div *ngFor="let category of categories; let i = index" [ngClass]="{'w-layout-grid uui-table_row': true, 'background-color-gray50': i % 2 === 1}">
            <div class="uui-table_feature">
              <div class="uui-pricing07_row-lead-text">                                
                <input type="text" class="expense-input" [(ngModel)]="category.category_name"/>
              </div>
            </div>
            <div class="uui-table_row">
              <div class="uui-pricing07_row-lead-text">   
                {{category.average_monthly_expense | number:'1.2-2'}}
              </div>
            </div>
            <div class="uui-table_row">
              <div class="action">
                <button type="button" class="btn btn-warning" (click)="updateCategory(i)">Save</button>
                <button type="button" class="btn btn-danger" (click)="deleteCategory(i)">Delete</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

// plan-wise-react-php/frontend/src/pages/Categories.tsx
import React, { useState, useEffect } from 'react';
import category from '../services/category-service';
import './Categories.css';

function Categories() {
  const [categories, setCategories] = useState([]);
  const [newCategory, setNewCategory] = useState("");
  const [showInput, setShowInput] = useState(false);

  useEffect(() => {
    fetchCategories();
  }, []);

  async function fetchCategories() {
    try {
      let response = await category.getAll();
      setCategories(response.category || []);
    } catch(exception){
      console.log(exception);
    }
  }

  async function createCategory() {
    if (newCategory) {
      let body = {
        category_name: newCategory
      };
      try {
        let response = await category.create(body);
        if (response.success) {
          setCategories([...categories, {
            id: response.category.id,
            category_name: newCategory,
            average_monthly_expense: 0
          }]);
          setNewCategory("");
        } else {
          console.error(response.message);
        }
      } catch (exception) {
        console.error(exception);
      }
    } else {
      console.warn("Please enter a category name");
    }
  }

  async function updateCategory(index){
    await category.update(categories[index].id, {
      category_name: categories[index].category_name
    });
  }

  async function deleteCategory(index){
    let response = await category.delete(categories[index].id);
    if(response.success){
      setCategories(categories.filter((_, i) => i !== index));
    }
  }

  return (
    <div className="uui-page-padding">
      <div className="uui-container-large">
        <div className="uui-padding-vertical-xhuge">
          <div className="uui-text-align-center">
            <div className="uui-max-width-large align-center">
              <h2 className="uui-heading-medium">Categories</h2>
              <div className="uui-space-xsmall"></div>
              <div className="uui-text-size-large">Add and manage your expense <strong>categories</strong></div>
              <button className="button w-button" onClick={() => setShowInput(!showInput)}>+</button>
            </div>
          </div>
          <div className="uui-table">
            <div className="uui-table_heading-row">
              <div className="uui-table_heading-row-text">Category Name</div>
              <div className="uui-table_heading-row-text">Monthly Average</div>
              <div className="uui-table_heading-row-text">Action</div>
            </div>
            {showInput && 
              <input 
                id="new-category" 
                value={newCategory}
                onChange={(e) => setNewCategory(e.target.value)}
                type="text" 
                className="w-layout-grid uui-table_row new-row uui-table_feature uui-pricing07_row-lead-text w-100"
                onKeyPress={(e) => e.key === 'Enter' && createCategory()}
              />
            }
            {categories.map((category, index) => (
              <div key={category.id} className={`w-layout-grid uui-table_row ${index % 2 === 1 ? "background-color-gray50" : ""}`}>
                <div className="uui-table_feature">
                  <div className="uui-pricing07_row-lead-text">                                
                    <input type="text" className="expense-input" value={category.category_name} onChange={(e) => {
                      const newCategories = [...categories];
                      newCategories[index].category_name = e.target.value;
                      setCategories(newCategories);
                    }}/>
                  </div>
                </div>
                <div className="uui-table_row">
                  <div className="uui-pricing07_row-lead-text">   
                    ${category.average_monthly_expense.toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </div>
                </div>
                <div className="uui-table_row">
                  <div className="action">
                    <button type="button" className="btn btn-warning" onClick={() => updateCategory(index)}>Save</button>
                    <button type="button" className="btn btn-danger" onClick={() => deleteCategory(index)}>Delete</button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export default Categories;
