// plan-wise-react-php/frontend/src/components/IncomeModal.tsx
import React, { useState, useEffect, forwardRef } from "react";
import categoryAPI from '../services/category-service';
import incomeAPI from '../services/income-service';
import './IncomeModal.css';

const IncomeModal = forwardRef<any, any>((props: any, ref: any) => {
    const [localHeaderSource, setLocalHeaderSource] = useState<any>("");
    const [localHeaderAmount, setLocalHeaderAmount] = useState<any>(0);
    const [localSelectedDate, setLocalSelectedDate] = useState<any>(props.selectedDate);
    const [localSelectedClassHeader, setLocalSelectedClassHeader] = useState<any>("");
    const [localSelectedOptionHeader, setLocalSelectedOptionHeader] = useState<any>("");
    const [options] = useState<any>([
        { text: 'Daily', class: 'daily' },
        { text: 'Weekly', class: 'weekly' },
        { text: 'Every Other Week', class: 'every-other-week' },
        { text: 'Monthly', class: 'monthly' },
        { text: 'Quarterly', class: 'quarterly' },
        { text: 'Every 6 Months', class: 'every-6-months' },
        { text: 'Annually', class: 'annually' },
        { text: 'One Time', class: 'one-time-expense' }
    ]);
    const [categories, setCategories] = useState<any>([]);

    useEffect(() => {
        categoryAPI.getAll().then((response: any) => {
            setCategories(response.category || []);
        });
        onShow();
    }, []);

    useEffect(() => {
        const observer = new MutationObserver((mutationsList: any) => {
            for (let mutation of mutationsList) {
                if (mutation.type === 'attributes' && mutation.attributeName === 'class') {
                    if (ref.current.className.includes("show")) {
                        onShow();
                    }
                }
            }
        });

        observer.observe(ref.current, { attributes: true });

        return () => {
            observer.disconnect();
        };
    }, [
        props.headerSource,
        props.headerAmount,
        props.selectedDate,
        props.selectedClassHeader,
        props.selectedOptionHeader,
        props.selectedClassCategoryHeader,
        props.selectedOptionCategoryHeader
    ]);

    const onShow = () => {
        setLocalHeaderSource(props.headerSource);
        setLocalHeaderAmount(props.headerAmount);
        setLocalSelectedDate((new Date(props.selectedDate)).toISOString().substring(0, 10));
        setLocalSelectedClassHeader(props.selectedClassHeader);
        setLocalSelectedOptionHeader(props.selectedOptionHeader);
    };

    const selectOptionHeader = (option: any) => {
        setLocalSelectedOptionHeader(option.text);
        setLocalSelectedClassHeader(option.class);
    };

    const createIncome = async () => {
        try {
            let body = {
                source: localHeaderSource,
                amount: localHeaderAmount,
                start_date: localSelectedDate,
                frequency: options.findIndex((x: any) => localSelectedClassHeader === x.class)
            };
            console.log(body);
            let response = await incomeAPI.create(body);
            if (response.success) {
                props.onModalClosed();
            } else {
                console.error(response.message);
            }
        } catch (exception: any) {
            console.error(exception);
        }
    };

    return (
        <div ref={ref} className="modal fade" id="incomeModal" tabIndex={-1} role="dialog" aria-labelledby="incomeModalLabel" aria-hidden="true">
            <div className="modal-dialog" role="document">
                <div className="modal-content">
                    <div className="modal-header">
                        <h5 className="modal-title" id="incomeModalLabel">New Income</h5>
                        <button type="button" className="close" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div className="modal-body">
                        <div className="income-expense-input">
                            <div className="income-expense-row">
                                <span>Source: </span>
                                <input type="text" className="expense-input modal-input" value={localHeaderSource} onChange={e => setLocalHeaderSource(e.target.value)} />
                            </div>
                            <div className="income-expense-row">
                                <span>Amount($): </span>
                                <input type="number" className="expense-input modal-input" value={localHeaderAmount} onChange={e => setLocalHeaderAmount(e.target.value)} />
                            </div>
                            <div className="income-expense-row">
                                <span>Date: </span>
                                <input type="date" pattern="\d{4}-\d{2}-\d{2}" disabled={true} className="expense-input modal-input" value={localSelectedDate} onChange={e => setLocalSelectedDate(e.target.value)} />
                            </div>
                            <div className="income-expense-row">
                                <span>Frequency: </span>
                                <div className="dropdown dropdown-border modal-input" data-bs-toggle="dropdown" data-bs-display="static">
                                    <button className={`btn dropdown-toggle ${localSelectedClassHeader}`} type="button" id="dropdownMenuButtonHeader" aria-expanded="false">
                                        {localSelectedOptionHeader}
                                    </button>
                                    <span className="dropdown-icon">▼</span>
                                    <ul className="dropdown-menu" aria-labelledby="dropdownMenuButtonHeader">
                                        <li className="mt-1">
                                            <a className="dropdown-item" href="#" onClick={() => selectOptionHeader({ text: '', class: '' })}>Select Interval</a>
                                        </li>
                                        {options.map((option: any) => (
                                            <li key={option.text} className="mt-1">
                                                <a className={`${option.class} dropdown-item`} href="#" onClick={() => selectOptionHeader(option)}>{option.text}</a>
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="modal-footer">
                        <button type="button" className="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" className="btn btn-primary" onClick={createIncome}>Save changes</button>
                    </div>
                </div>
            </div>
        </div>
    );
});

export default IncomeModal;

// plan-wise-angular-java/frontend/src/app/components/income-modal/income-modal.component.ts
import { Component, Input, OnInit, ViewChild, ElementRef } from '@angular/core';
import * as bootstrap from 'bootstrap';
import { CategoryService } from '../../../services/category.service';
import { IncomeService } from '../../../services/income.service';

@Component({
  selector: 'app-income-modal',
  templateUrl: './income-modal.component.html',
  styleUrls: ['./income-modal.component.css', '../../../assets/components.css', '../../../assets/budgeting-app.css']
})
export class IncomeModalComponent implements OnInit {
  @Input() headerSource: string = '';
  @Input() headerAmount: number = -1;
  @Input() selectedDate: string = '';
  @Input() selectedClassHeader: string = '';
  @Input() selectedOptionHeader: string = '';
  @Input() onModalClosed: any;
  @ViewChild('incomeModal') incomeModal!: ElementRef;
  localHeaderSource: string = '';
  localHeaderAmount: number = -1;
  localSelectedDate: string = '';
  localSelectedClassHeader: string = '';
  localSelectedOptionHeader: string = '';
  options: any[] = [
    { text: 'Daily', class: 'daily' },
    { text: 'Weekly', class: 'weekly' },
    { text: 'Every Other Week', class: 'every-other-week' },
    { text: 'Monthly', class: 'monthly' },
    { text: 'Quarterly', class: 'quarterly' },
    { text: 'Every 6 Months', class: 'every-6-months' },
    { text: 'Annually', class: 'annually' },
    { text: 'One Time', class: 'one-time-expense' }
  ];
  categories: any[] = [];
  modalInstance: any;

  constructor(private categoryService: CategoryService, private incomeService: IncomeService) { }

  ngOnInit(): void {
    this.categoryService.getAll().then((response: any)=> {
      this.categories = response.category || [];
    });
    this.onShow();
  }

  onShow(): void {
    this.localHeaderSource = this.headerSource;
    this.localHeaderAmount = this.headerAmount;
    this.localSelectedDate = new Date(this.selectedDate).toISOString().substring(0, 10);
    this.localSelectedClassHeader = this.selectedClassHeader;
    this.localSelectedOptionHeader = this.selectedOptionHeader;
  }

  selectOptionHeader(option: any): void {
    this.localSelectedOptionHeader = option.text;
    this.localSelectedClassHeader = option.class;
  }

  async createIncome(): Promise<void> {
    try {
      let body = {
        source: this.localHeaderSource,
        amount: this.localHeaderAmount,
        start_date: this.localSelectedDate,
        frequency: this.options.findIndex(x => this.localSelectedClassHeader === x.class)
      };
      console.log(body);
      let response: any = await this.incomeService.create(body);
      if (response.success) {
        this.onModalClosed();
      } else {
        console.error(response.message);
      }
    } catch (exception) {
      console.error(exception);
    }
  }

  open() {
    this.modalInstance = new bootstrap.Modal(this.incomeModal.nativeElement);
    this.modalInstance.show();
  }

  close() {
    this.modalInstance.hide();
  }
}

<div #incomeModal class="modal fade" id="incomeModal" tabindex="-1" role="dialog" aria-labelledby="incomeModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="incomeModalLabel">New Income</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="income-expense-input">
                    <div class="income-expense-row">
                        <span>Source: </span>
                        <input type="text" class="expense-input modal-input" [(ngModel)]="localHeaderSource" />
                    </div>
                    <div class="income-expense-row">
                        <span>Amount($): </span>
                        <input type="number" class="expense-input modal-input" [(ngModel)]="localHeaderAmount" />
                    </div>
                    <div class="income-expense-row">
                        <span>Date: </span>
                        <input type="date" pattern="\d{4}-\d{2}-\d{2}" disabled="true" class="expense-input modal-input" [(ngModel)]="localSelectedDate" />
                    </div>
                    <div class="income-expense-row">
                        <span>Frequency: </span>
                        <div class="dropdown dropdown-border modal-input" data-bs-toggle="dropdown" data-bs-display="static">
                            <button class="btn dropdown-toggle" [ngClass]="localSelectedClassHeader" type="button" id="dropdownMenuButtonHeader" aria-expanded="false">
                                {{localSelectedOptionHeader}}
                            </button>
                            <span class="dropdown-icon">▼</span>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButtonHeader">
                                <li class="mt-1">
                                    <a class="dropdown-item" href="javascript:void(0)" (click)="selectOptionHeader({ text: '', class: '' })">Select Interval</a>
                                </li>
                                <li *ngFor="let option of options" class="mt-1">
                                    <a class="dropdown-item" [ngClass]="option.class" href="javascript:void(0)" (click)="selectOptionHeader(option)">{{option.text}}</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" (click)="createIncome()">Save changes</button>
            </div>
        </div>
    </div>
</div>
