// plan-wise-react-node/frontend/src/pages/Login.js
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import account from '../services/account-service';
import { storageHandler } from '../utils/storage_handler';
import '../assets/components.css';
import '../assets/budgeting-app.css';

function Login() {
  const navigate = useNavigate();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [token, setToken] = useState(storageHandler.localStorageGet('token'));

  
  useEffect(() => {
    if (token) {
        navigate('/');
    }
  }, [token]);

  const submitForm = async (event) => {
    event.preventDefault();

    const response = await account.login({ username, password });
    if (response.success) {
        storageHandler.localStorageSet("token", response.token);
        setToken(response.token);
        navigate('/');
    } else {
        setError(response.message);
    }
  };

  return (
    <div className="container w-container">
      <div className="form-wrapper">
        <div className="w-form">
          <form id="wf-form-signup" onSubmit={submitForm}>
            <h1 className="heading">Login</h1>
            <div>
              <label htmlFor="email" className="field-label-2">Email</label>
              <input 
                type="email" 
                className="text-field w-input" 
                maxLength="256" 
                name="email" 
                data-name="email" 
                placeholder="e.g. howard.thurman@gmail.com" 
                id="username"
                value={username}
                onChange={e => setUsername(e.target.value)}
                required
              />
            </div>
            <div>
              <label htmlFor="password-2" className="field-label">Password</label>
              <input 
                type="password" 
                className="text-field-2 w-input" 
                maxLength="256" 
                placeholder="" 
                id="password-2" 
                data-ms-member="password"
                value={password}
                onChange={e => setPassword(e.target.value)}
                required
              />
            </div>
            <div className="relative w-clearfix">
              <a href="#" className="forgot-password-link">Forgot password</a>
            </div>
            <button className="uui-button-4 button-width w-button">Login</button>
            <div>
              {error && <div className="alert alert-danger" role="alert">{error}</div>}
            </div>
          </form>
        </div>
        <div>
          <div className="text-block-2">Need an account? <a href="/registration">Sign up</a></div>
        </div>
      </div>
    </div>
  );
}

export default Login;

// plan-wise-angular-java/frontend/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AccountService } from '../../../services/account.service';
import { StorageHandler as storageHandler } from '../../../utils/storage.handler';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['../../../assets/components.css', '../../../assets/budgeting-app.css']
})
export class LoginComponent {
  username: string|null = '';
  password: string|null  = '';
  error: string|null  = '';
  token: string|null  = '';

  constructor(private router: Router, private accountService: AccountService) {
    this.token = storageHandler.localStorageGet('token');
    if (this.token) {
      this.router.navigate(['/']);
    }
  }

  async submitForm() {
    const response: any = await this.accountService.login({ username: this.username, password: this.password });
    if (response.success) {
      storageHandler.localStorageSet('token', response.token);
      this.token = response.token;
      this.router.navigate(['/']);
    } else {
      this.error = response.message;
    }
  }
}

<div class="container w-container">
    <div class="form-wrapper">
        <div class="w-form">
            <form id="wf-form-signup" (ngSubmit)="submitForm()">
            <h1 class="heading">Login</h1>
            <div>
                <label for="email" class="field-label-2">Email</label>
                <input 
                type="email" 
                class="text-field w-input" 
                maxLength="256" 
                name="email" 
                data-name="email" 
                placeholder="e.g. howard.thurman@gmail.com" 
                id="username"
                [(ngModel)]="username"
                required
                />
            </div>
            <div>
                <label for="password-2" class="field-label">Password</label>
                <input 
                type="password" 
                class="text-field-2 w-input" 
                maxLength="256" 
                placeholder="" 
                id="password-2" 
                [(ngModel)]="password"
                required
                />
            </div>
            <div class="relative w-clearfix">
                <a href="#" class="forgot-password-link">Forgot password</a>
            </div>
            <button class="uui-button-4 button-width w-button">Login</button>
            <div>
                <div *ngIf="error" class="alert alert-danger" role="alert">{{error}}</div>
            </div>
            </form>
        </div>
        <div>
            <div class="text-block-2">Need an account? <a routerLink="/registration">Sign up</a></div>
        </div>
    </div>
</div>
