// plan-wise-react-php/frontend/src/components/ExpenseModal.tsx
import React, { useState, useEffect, ForwardedRef } from "react";
import categoryAPI from '../services/category-service';
import expenseAPI from '../services/expense-service';
import './ExpenseModal.css';

interface ExpenseModalProps {
  headerExpense: string;
  headerAmount: number;
  selectedDate: string;
  selectedClassHeader: string;
  selectedOptionHeader: string;
  selectedOption: string;
  selectedClass: string;
  headerDate: Date;
  selectedClassCategoryHeader: string;
  selectedOptionCategoryHeader: any;
  onModalClosed: () => void;
}

const ExpenseModal = React.forwardRef(
  (
    {
      headerExpense,
      headerAmount,
      selectedDate,
      selectedClassHeader,
      selectedOptionHeader,
      selectedOption,
      selectedClass,
      selectedClassCategoryHeader,
      selectedOptionCategoryHeader,
      onModalClosed,
    }: ExpenseModalProps,
    ref: any
  ) => {
    const [localHeaderExpense, setLocalHeaderExpense] = useState<string>('');
    const [localHeaderAmount, setLocalHeaderAmount] = useState<number>(0);
    const [localSelectedDate, setLocalSelectedDate] = useState<string>(selectedDate);
    const [localSelectedClassHeader, setLocalSelectedClassHeader] = useState<string>('');
    const [localSelectedOptionHeader, setLocalSelectedOptionHeader] = useState<string>('');
    const [localSelectedClassCategoryHeader, setLocalSelectedClassCategoryHeader] = useState<string>('');
    const [localSelectedOptionCategoryHeader, setLocalSelectedOptionCategoryHeader] = useState<any>('');
    const [options] = useState([
      { text: 'Daily', class: 'daily' },
      { text: 'Weekly', class: 'weekly' },
      { text: 'Every Other Week', class: 'every-other-week' },
      { text: 'Monthly', class: 'monthly' },
      { text: 'Quarterly', class: 'quarterly' },
      { text: 'Every 6 Months', class: 'every-6-months' },
      { text: 'Annually', class: 'annually' },
      { text: 'One Time', class: 'one-time-expense' }
    ]);
    const [categories, setCategories] = useState<any[]>([]);

    useEffect(() => {
      categoryAPI.getAll().then(response => {
        setCategories(response.category || []);
      });
      onShow();
    }, []);

    useEffect(() => {
      const observer = new MutationObserver((mutationsList) => {
        for (let mutation of mutationsList) {
          if (mutation.type === 'attributes' && mutation.attributeName === 'class') {
            if (ref.current?.className.includes("show")) {
              onShow();
            }
          }
        }
      });

      observer.observe(ref.current!, { attributes: true });

      return () => {
        observer.disconnect();
      };
    }, [
      headerExpense, 
      headerAmount, 
      selectedDate, 
      selectedClassHeader, 
      selectedOptionHeader, 
      selectedClassCategoryHeader, 
      selectedOptionCategoryHeader
    ]);

    const onShow = () => {
      setLocalHeaderExpense(headerExpense);
      setLocalHeaderAmount(headerAmount);
      setLocalSelectedDate((new Date(selectedDate)).toISOString().substring(0, 10));
      setLocalSelectedClassHeader(selectedClassHeader);
      setLocalSelectedOptionHeader(selectedOptionHeader);
      setLocalSelectedClassCategoryHeader(selectedClassCategoryHeader);
      setLocalSelectedOptionCategoryHeader(selectedOptionCategoryHeader);
    };

    const selectOptionHeader = (option: { text: string, class: string }) => {
      setLocalSelectedOptionHeader(option.text);
      setLocalSelectedClassHeader(option.class);
    };

    const selectCategoryHeader = (category: any) => {
      setLocalSelectedOptionCategoryHeader(category);
      setLocalSelectedClassCategoryHeader(category.category_name === 'Select Category' ? '' : 'btn-primary');
    };

    const createExpense = async () => {
      try {
        const body = {
          expenses: localHeaderExpense,
          amount: localHeaderAmount,
          start_date: localSelectedDate,
          frequency: options.findIndex(x => localSelectedClassHeader === x.class),
          category: localSelectedOptionCategoryHeader.id
        };
        console.log(body);
        const response = await expenseAPI.create(body);
        if (response.success) {
          onModalClosed();
        } else {
          console.error(response.message);
        }
      } catch (exception) {
        console.error(exception);
      }
    };

    return (
      <div ref={ref} className="modal fade" id="expenseModal" tabIndex={-1} role="dialog" aria-labelledby="expenseModalLabel" aria-hidden="true">
        <div className="modal-dialog" role="document">
          <div className="modal-content">
            <div className="modal-header">
              <h5 className="modal-title" id="expenseModalLabel">New Expense</h5>
              <button type="button" className="close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div className="modal-body">
              <div className="income-expense-input">
                <div className="income-expense-row">
                  <span>Expense: </span>
                  <input type="text" className="expense-input modal-input" value={localHeaderExpense} onChange={e => setLocalHeaderExpense(e.target.value)} />
                </div>
                <div className="income-expense-row">
                  <span>Amount($): </span>
                  <input type="number" className="expense-input modal-input" value={localHeaderAmount} onChange={e => setLocalHeaderAmount(Number(e.target.value))} />
                </div>
                <div className="income-expense-row">
                  <span>Date: </span>
                  <input type="date" pattern="\d{4}-\d{2}-\d{2}" disabled={true} className="expense-input modal-input" value={localSelectedDate} onChange={e => setLocalSelectedDate(e.target.value)} />
                </div>
                <div className="income-expense-row">
                  <span>Frequency: </span>
                  <div className="dropdown dropdown-border modal-input" data-bs-toggle="dropdown" data-bs-display="static">
                    <button className={`btn dropdown-toggle ${localSelectedClassHeader}`} type="button" id="dropdownMenuButtonHeader" aria-expanded="false">
                      {localSelectedOptionHeader}
                    </button>
                    <span className="dropdown-icon">▼</span>
                    <ul className="dropdown-menu" aria-labelledby="dropdownMenuButtonHeader">
                      <li className="mt-1">
                        <a className="dropdown-item" href="#" onClick={() => selectOptionHeader({ text: '', class: '' })}>Select Interval</a>
                      </li>
                      {options.map(option => (
                        <li key={option.text} className="mt-1">
                          <a className={`${option.class} dropdown-item`} href="#" onClick={() => selectOptionHeader(option)}>{option.text}</a>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
                <div className="income-expense-row">
                  <span>Category: </span>
                  <div className="dropdown dropdown-border  modal-input" data-bs-toggle="dropdown" data-bs-display="static">
                    <button className={`btn dropdown-toggle ${localSelectedClassCategoryHeader}`} type="button" id="dropdownCategoryButtonHeader" aria-expanded="false">
                      {localSelectedOptionCategoryHeader?.category_name || "Select Category"}
                    </button>
                    <span className="dropdown-icon">▼</span>
                    <ul className="dropdown-menu" aria-labelledby="selectCategoryHeader">
                      <li className="mt-1">
                        <a className="dropdown-item" href="#" onClick={() => selectCategoryHeader({ category_name: 'Select Category' })}>Select Category</a>
                      </li>
                      {categories.map(category => (
                        <li key={category.id}>
                          <a className="one-time-expense dropdown-item" href="#" onClick={() => selectCategoryHeader(category)}>{category.category_name}</a>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div className="modal-footer">
              <button type="button" className="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" className="btn btn-primary" onClick={createExpense}>Save changes</button>
            </div>
          </div>
        </div>
      </div>
    );
  }
);

export default ExpenseModal;

// plan-wise-vue-python/frontend/src/components/ExpenseModal.vue
<template>
    
    <div class="modal fade" id="expenseModal" ref="expenseModal" tabindex="-1" role="dialog" aria-labelledby="expenseModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="expenseModalLabel">New Expense</h5>
            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="income-expense-input">
              <div class="income-expense-row">
                <span>Expense: </span>
                <input type="text" class="expense-input modal-input" v-model="localHeaderExpense">
              </div>
              <div class="income-expense-row">
                <span>Amount($): </span>
                <input type="number" class="expense-input modal-input" v-model="localHeaderAmount">
              </div>
              <div class="income-expense-row">
                <span>Date: </span>
                <input type="date" pattern="\d{4}-\d{2}-\d{2}" disabled="true" class="expense-input modal-input" v-model="localSelectedDate">
              </div>
              <div class="income-expense-row">
                <span>Frequency: </span>
                <div class="dropdown dropdown-border modal-input" data-bs-toggle="dropdown" data-bs-display="static">
                  <button :class="['btn', 'dropdown-toggle', localSelectedClassHeader]" type="button" id="dropdownMenuButtonHeader" aria-expanded="false">
                    {{ localSelectedOptionHeader }}
                  </button>
                  <span class="dropdown-icon">▼</span>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButtonHeader">
                    <li class="mt-1">
                      <a class="dropdown-item" href="#" @click="selectOptionHeader('', '')">Select Interval</a>
                    </li>
                    <li v-for="option in options" :key="option.text" class="mt-1">
                      <a :class="[option.class, 'dropdown-item']" href="#" @click="selectOptionHeader(option)">{{ option.text }}</a>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="income-expense-row">
                <span>Category: </span>
                <div class="dropdown dropdown-border  modal-input" data-bs-toggle="dropdown" data-bs-display="static">
                  <button :class="['btn', 'dropdown-toggle', localSelectedClassCategoryHeader]" type="button" id="dropdownCategoryButtonHeader" aria-expanded="false">
                    {{ localSelectedOptionCategoryHeader?.category_name || "Select Category" }}
                  </button>
                  <span class="dropdown-icon">▼</span>
                  <ul class="dropdown-menu" aria-labelledby="selectCategoryHeader">
                    <li class="mt-1">
                      <a class="dropdown-item" href="#" @click="selectCategoryHeader({ category_name: 'Select Category' })">Select Category</a>
                    </li>
                    <li v-for="category in categories" :key="category.id">
                      <a :class="['one-time-expense', 'dropdown-item']" href="#" @click="selectCategoryHeader(category)">{{ category.category_name }}</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" @click="createExpense">Save changes</button>
          </div>
        </div>
      </div>
    </div>
</template>
<style scoped>
@import '../assets/components.css';
@import '../assets/budgeting-app.css';
.expense-input{
  width: 100%;
  padding: 5px;
  border-radius: 5px;
  border: 1px solid rgba(0, 0, 0, .1);
  background: transparent;
  font-family: system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Noto Sans,Ubuntu,Cantarell,Helvetica Neue,Oxygen,Fira Sans,Droid Sans,sans-serif;
    font-size: 1.125rem;
}

.expense-cell {
  padding: 15px !important;
}
.modal-input {
  width: 50% !important;
}
.income-expense-input{
  display: flex;
  flex-direction: column;
  row-gap: 15px;
}
.income-expense-row{
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}
.dropdown-menu{
  padding-left: 10px !important;
  padding-right: 10px !important;
}
.dropdown-icon {
  position: absolute;
  right: 10px;
  top: 50%;
  transform: translateY(-50%);
}
.btn.dropdown-toggle::after {
  display: none;
}
</style>
<script>
import categoryAPI from '../services/category-service';
import expenseAPI from '../services/expense-service';
export default {
    props: [
        'selectedOptionCategoryHeader',
        'selectedClassCategoryHeader',
        'selectedOptionHeader',
        'selectedClassHeader',
        'selectedOption',
        'selectedClass',
        'headerSource',
        'headerAmount',
        'headerDate',
        'selectedDate'
    ],
    data() {
        return {
            localSelectedOptionCategoryHeader: '',
            localSelectedClassCategoryHeader: '',
            localSelectedOptionHeader: '',
            localSelectedClassHeader: '',
            localSelectedOption: '',
            localSelectedClass: '',
            localHeaderSource: '',
            localHeaderAmount: 0,
            localHeaderDate: '',
            localSelectedDate: '',
            localHeaderExpense: '',
            options: [
                { text: 'Daily', class: 'daily' },
                { text: 'Weekly', class: 'weekly' },
                { text: 'Every Other Week', class: 'every-other-week' },
                { text: 'Monthly', class: 'monthly' },
                { text: 'Quarterly', class: 'quarterly' },
                { text: 'Every 6 Months', class: 'every-6-months' },
                { text: 'Annually', class: 'annually' },
                { text: 'One Time', class: 'one-time-expense' }
            ],
            categories: []
        };
    },
    mounted() {
        categoryAPI.getAll().then(response => {
            this.categories = response.category || [];
        });
        this.onShow();
    },
    methods: {
      async createExpense(){
          try {
          let body = {
                  expenses: this.localHeaderExpense,
                  amount: this.localHeaderAmount,
                  start_date: this.localSelectedDate,
                  frequency: this.options.findIndex(x => this.localSelectedClassHeader === x.class),
                  category: this.localSelectedOptionCategoryHeader.id
              };
              console.log(body)
              let response = await expenseAPI.create(body);
              if (response.success) {
                  this.$emit('modal-closed');
              } else {
                console.error(response.message);
              }
          } catch (exception) {
              console.error(exception);
          }
      },
      onShow(){         
          this.localSelectedOptionCategoryHeader = this.selectedOptionCategoryHeader;
          this.localSelectedClassCategoryHeader = this.selectedClassCategoryHeader;
          this.localSelectedOptionHeader = this.selectedOptionHeader;
          this.localSelectedClassHeader = this.selectedClassHeader;
          this.localSelectedOption = this.selectedOption;
          this.localSelectedClass = this.selectedClass;
          this.localHeaderExpense = this.headerExpense;
          this.localHeaderAmount = this.headerAmount;
          this.localHeaderDate = this.headerDate;
          this.localSelectedDate = this.selectedDate;
      },
      selectOptionHeader(option) {
          this.localSelectedOptionHeader = option.text;
          this.localSelectedClassHeader = option.class;
      },
      selectCategoryHeader(category) {
          this.localSelectedOptionCategoryHeader = category;
          this.localSelectedClassCategoryHeader = category.category_name === 'Select Category'? '' : 'btn-primary';
      },
    },
};
</script>
