// plan-wise-angular-java/frontend/src/app/pages/expenses/expenses.component.ts
import { Component, OnInit, AfterViewInit, ElementRef, ViewChild } from '@angular/core';
import { DatePipe } from '@angular/common';
import { Modal } from 'bootstrap';
import { ExpenseService } from '../../../services/expense.service';
import { CategoryService } from '../../../services/category.service';
import * as moment from 'moment';
import { ConfirmationModalComponent } from '../../components/confirmation-modal/confirmation-modal.component';

@Component({
  selector: 'app-expense',
  providers: [DatePipe],
  templateUrl: './expenses.component.html',
  styleUrls: ['./expenses.component.css', '../../../assets/components.css', '../../../assets/budgeting-app.css']
})
export class ExpensesComponent implements OnInit, AfterViewInit {
  @ViewChild(ConfirmationModalComponent) confirmationModal!: ConfirmationModalComponent;
  selectedOptionCategoryHeader = { category_name: 'Select Category', id: -1 };
  selectedClassCategoryHeader = '';
  selectedOptionHeader = 'Select Interval';
  selectedClassHeader = '';
  selectedOption = 'Select Interval';
  selectedClass = '';
  headerExpense = '';
  headerAmount = 0;
  headerDate = new Date();
  selectedDate = new Date();
  showInput = false;
  deleteBodyMessage = '';
  selectedExpenseIndex = -1;
  options = [
    { text: 'Daily', class: 'daily' },
    { text: 'Weekly', class: 'weekly' },
    { text: 'Every Other Week', class: 'every-other-week' },
    { text: 'Monthly', class: 'monthly' },
    { text: 'Quarterly', class: 'quarterly' },
    { text: 'Every 6 Months', class: 'every-6-months' },
    { text: 'Annually', class: 'annually' },
    { text: 'One Time', class: 'one-time-expense' }
  ];
  rows: any = [];
  categories: any = [];

  constructor(private elRef: ElementRef, private expenseService: ExpenseService, private categoryService: CategoryService) { }

  ngOnInit() {
    this.fetchCategories().then(() => {
      this.fetchExpenses();
    });
    document.title = "Plan Wise - Expenses";
  }

  ngAfterViewInit() {
    const dropdownElements = this.elRef.nativeElement.querySelectorAll('[data-bs-toggle="dropdown"]');
    for (let i = 0; i < dropdownElements.length; i++) {
      new Modal(dropdownElements[i]);
    }
  }

  selectOption(option: any, index: number) {
    this.rows[index].frequency = this.options.findIndex(x => option.class === x.class);
  }

  selectOptionHeader(option: any) {
    this.selectedOptionHeader = option.text;
    this.selectedClassHeader = option.class;
  }

  selectCategoryOption(category: any, index: number) {
    if (!category) {
      this.rows[index].category = null;
      return;
    }
    this.rows[index].category = category.id;
  }

  selectCategoryHeader(category: any) {
    this.selectedOptionCategoryHeader = category;
    this.selectedClassCategoryHeader = category ? 'btn-primary' : '';
  }

  formattedDate() {
    return moment(this.selectedDate).format('MM-DD-YYYY');
  }

  async createExpense() {
    if (this.headerExpense) {
      let body = {
        expenses: this.headerExpense,
        amount: this.headerAmount,
        start_date: this.headerDate,
        frequency: this.options.findIndex(x => this.selectedClassHeader === x.class),
        category: this.selectedOptionCategoryHeader.id
      };
      try {
        let response: any = await this.expenseService.create(body);
        if (response.success) {
          this.rows.push(response.expense);
          this.headerExpense = "";
          this.headerAmount = 0;
          this.headerDate = new Date();
          this.selectOptionHeader('Select Interval');
          this.selectCategoryHeader({ categoryName: 'Select Category' });
        } else {
          console.error(response.message);
        }
      } catch (exception) {
        console.error(exception);
      }
    } else {
      console.warn("Please enter a category name");
    }
  }

  async fetchCategories() {
    try {
      let response: any = await this.categoryService.getAll();
      this.categories = response.categories || [];
    } catch (exception) {
      console.log(exception);
    }
  }

  async fetchExpenses() {
    try {
      let response: any = await this.expenseService.getAll();
      this.rows = response.expenses || [];
    } catch (exception) {
      console.log(exception);
    }
  }

  async updateExpense(index: number) {
    let data = Object.assign({}, this.rows[index]);
    delete data.user;
    data.category = data.category.id;
    let response: any = await this.expenseService.update(this.rows[index].id, data);
    console.log(response);
  }

  deleteConfirmation(index: number) {
    this.selectedExpenseIndex = index;
    this.deleteBodyMessage = `Are you sure you want to delete ${this.rows[index].expenses}?`;
    this.confirmationModal.changeModalMessage(`Delete ${this.rows[index].expenses}`, this.deleteBodyMessage, "Confirm", this.deleteExpense, index);
    this.confirmationModal.open();
  }

  deleteExpense = async () => {
    let index = this.selectedExpenseIndex;
    let response: any = await this.expenseService.delete(this.rows[index].id);
    if (response.success) {
      this.rows.splice(index, 1);
      this.confirmationModal.close();
    }
  }

  async inputToggle() {
    this.showInput = !this.showInput;
  }

  getButtonClass(index: number) {
    return this.categories.find((category: any) => category.id === this.rows[index].category.id) ? 'btn-primary' : '';
  }

  getCategoryName(index: number) {
    return this.categories.find((category: any) => category.id === this.rows[index].category.id)?.category_name || 'Select Category';
  }

  isNan(value: any) {
    return isNaN(value);
  }

  get conditionalLayoutGrid() {
    return {
      'w-layout-grid': window.innerWidth > 600,
      'uui-table_row': true,
      'new-row': true
    };
  }
}


<div class="uui-page-padding">
    <div class="uui-container-large">
        <div class="uui-padding-vertical-xhuge">
            <div class="uui-text-align-center">
                <div class="uui-max-width-large align-center">
                    <h2 class="uui-heading-medium">Expenses</h2>
                    <div class="uui-space-xsmall"></div>
                    <div class="uui-text-size-large">Add and manage your repeating <strong>expenses</strong></div>
                    <a href="javascript:void(0)" class="button w-button" (click)="inputToggle()">{{ showInput ? "-" : "+" }}</a>
                </div>                  
            </div>
            <div class="uui-table">
                <div class="uui-table_heading-row">
                    <div class="uui-table_heading-row-text">Expense</div>
                    <div class="uui-table_heading-row-text">Amount</div>
                    <div class="uui-table_heading-row-text">Start Date</div>
                    <div class="uui-table_heading-row-text">Frequency</div>
                    <div class="uui-table_heading-row-text">Category</div>
                    <div class="uui-table_heading-row-text">Action</div>
                </div>
                <div [ngClass]="conditionalLayoutGrid" *ngIf="showInput">
                    <div class="uui-table_feature input-header">
                        <input type="text" class="expense-input" [(ngModel)]="headerExpense" />
                    </div>
                    <div class="uui-table_row-content input-header">
                        <div class="expense-input">
                            <span class="input-group-addon">$</span>
                            <input type="number" class="no-border-input" [(ngModel)]="headerAmount" />
                        </div>
                    </div>
                    <div class="uui-table_row-content input-header">
                        <input type="date" pattern="\d{4}-\d{2}-\d{2}" class="expense-input" [(ngModel)]="headerDate" />
                    </div>
                    <div class="uui-table_row-content input-header">
                        <div class="dropdown dropdown-border" data-bs-toggle="dropdown" data-bs-display="static">
                        <button [ngClass]="['btn', 'dropdown-toggle', 'frequency-width', selectedClassHeader]" type="button" id="dropdownMenuButtonHeader" aria-expanded="false">
                            {{ selectedOptionHeader }}
                        </button>
                        <span class="dropdown-icon">▼</span>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButtonHeader">
                            <li *ngFor="let option of options">
                            <a [ngClass]="[option.class, 'dropdown-item']" href="#" (click)="selectOptionHeader(option)">{{ option.text }}</a>
                            </li>
                        </ul>
                        </div>
                    </div>
                    <div class="uui-table_row-content input-header">
                        <div class="dropdown dropdown-border" data-bs-toggle="dropdown" data-bs-display="static">
                            <button [ngClass]="['btn', 'dropdown-toggle', 'frequency-width', selectedClassCategoryHeader]" type="button" id="dropdownCategoryButtonHeader" aria-expanded="false">
                                {{ selectedOptionCategoryHeader.category_name || "Select Category" }}
                            </button>
                            <span class="dropdown-icon">▼</span>
                            <ul class="dropdown-menu" aria-labelledby="selectCategoryHeader">
                                <li>
                                    <a class="dropdown-item" (click)="selectCategoryHeader(null)">Select Category</a>
                                </li>
                                <li *ngFor="let category of categories">
                                    <a [ngClass]="['one-time-expense', 'dropdown-item', 'frequency-width']" (click)="selectCategoryHeader(category)">{{ category.category_name }}</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="uui-table_row-content input-header">
                        <button type="button" class="btn btn-primary add-button" (click)="createExpense()">Add</button>
                    </div>
                </div> 
                <div *ngFor="let row of rows; let index = index">
                    <div [ngClass]="['w-layout-grid', 'uui-table_row', 'background-color-gray50']">
                        <div class="uui-table_feature">
                        <input type="text" class="expense-input" [(ngModel)]="rows[index].expenses" />
                        </div>
                        <div class="uui-table_row-content">
                        <div class="expense-input">
                            <span class="input-group-addon">$</span>
                            <input type="number" class="no-border-input" [(ngModel)]="rows[index].amount" />
                        </div>
                        </div>
                        <div class="uui-table_row-content">
                            <input type="date" pattern="\d{4}-\d{2}-\d{2}" class="expense-input" [ngModel]="(rows[index].startDate | date:'yyyy-MM-dd') || null" />
                        </div>
                        <div class="uui-table_row-content">
                        <div class="dropdown dropdown-border" data-bs-toggle="dropdown" data-bs-display="static">
                            <button [ngClass]="['btn', 'frequency-width', 'dropdown-toggle', isNan(rows[index].frequency)? '': options[rows[index].frequency].class]" type="button" [id]="'dropdownMenuButton' + index" aria-expanded="false">
                            {{ isNan(rows[index].frequency)? 'Select Frequency': options[rows[index].frequency].text }}
                            </button>
                            <span class="dropdown-icon">▼</span>
                            <ul class="dropdown-menu" [attr.aria-labelledby]="'dropdownMenuButton' + index">
                            <li *ngFor="let option of options">
                                <a [ngClass]="[option.class, 'dropdown-item']" href="#" (click)="selectOption(option, index)">{{ option.text }}</a>
                            </li>
                            </ul>
                        </div>
                        </div>
                        <div class="uui-table_row-content">
                            <div class="dropdown dropdown-border" data-bs-toggle="dropdown" data-bs-display="static">
                            <button [ngClass]="['btn', 'dropdown-toggle', 'frequency-width', getButtonClass(index)]" type="button" [id]="'dropdownCategoryButton' + index" aria-expanded="false">
                                {{ getCategoryName(index) }}
                            </button>
                            <span class="dropdown-icon">▼</span>
                            <ul class="dropdown-menu" [attr.aria-labelledby]="'dropdownCategoryButton' + index">
                                <li>
                                    <a class="dropdown-item" (click)="selectCategoryOption(null, index)">Select Category</a>
                                </li>
                                <li *ngFor="let category of categories">
                                    <a [ngClass]="['one-time-expense', 'dropdown-item', 'frequency-width']" (click)="selectCategoryOption(category, index)">{{ category.category_name }}</a>
                                </li>
                            </ul>
                            </div>
                        </div>
                        <div class="uui-table_row-content">
                        <div class="action">
                            <button type="button" class="btn btn-warning" (click)="updateExpense(index)">Save</button>
                            <button type="button" class="btn btn-danger" (click)="deleteConfirmation(index)">Delete</button>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <app-confirmation-modal></app-confirmation-modal>
</div>

// plan-wise-react-node/frontend/src/pages/Expenses.js
import React, { useState, useEffect, useRef } from 'react';
import { Modal } from 'bootstrap';
import expense from '../services/expense-service';
import category from '../services/category-service';
import '../assets/components.css';
import '../assets/budgeting-app.css';
import './Expenses.css';
import ConfirmationModal from '../components/ConfirmationModal';


function Expenses() {
    const [selectedOptionCategoryHeader, setSelectedOptionCategoryHeader] = useState({ category_name: 'Select Category' });
    const [selectedClassCategoryHeader, setSelectedClassCategoryHeader] = useState('');
    const [selectedOptionHeader, setSelectedOptionHeader] = useState('Select Interval');
    const [selectedClassHeader, setSelectedClassHeader] = useState('');
    const [showInput, setShowInput] = useState(false);
    const [confirmationModal, setConfirmationModal] = useState(null);
    const [deleteBodyMessage, setDeleteBodyMessage] = useState('');
    const [selectedExpenseIndex, setSelectedExpenseIndex] = useState(-1);
    const options = [
      { text: 'Daily', class: 'daily' },
      { text: 'Weekly', class: 'weekly' },
      { text: 'Every Other Week', class: 'every-other-week' },
      { text: 'Monthly', class: 'monthly' },
      { text: 'Quarterly', class: 'quarterly' },
      { text: 'Every 6 Months', class: 'every-6-months' },
      { text: 'Annually', class: 'annually' },
      { text: 'One Time', class: 'one-time-expense' }
    ];
    const [rows, setRows] = useState([]);
    const [categories, setCategories] = useState([]);
    const [windowWidth, setWindowWidth] = useState(window.innerWidth);
    const confirmationModalRef = useRef();
    
    useEffect(() => {
        document.title = "Plan Wise - Expenses";
        const handleResize = () => {
          setWindowWidth(window.innerWidth);
        };
    
        window.addEventListener('resize', handleResize);
    
        fetchCategories().then(() => {
            fetchExpenses();
        });
        return () => {    
            window.removeEventListener('resize', handleResize);
        };
    }, []);
    useEffect(() => {
        if (confirmationModalRef.current) {
            setConfirmationModal(new Modal(confirmationModalRef.current));
        }
    }, [confirmationModalRef.current]);
    
  
    const selectOption = (option, index) => {
        const newRows = [...rows];
        newRows[index].frequency = options.findIndex(x => option["class"] === x["class"]);
        setRows(newRows);
    };
      
    const selectOptionHeader = (option) => {
        setSelectedOptionHeader(option.text);
        setSelectedClassHeader(option["class"]);
    };
      
    const selectCategoryOption = (category, index) => {
        const newRows = [...rows];
        newRows[index].category = category ? category.id : null;
        setRows(newRows);
    };
      
    const selectCategoryHeader = (category) => {
        setSelectedOptionCategoryHeader(category);
        setSelectedClassCategoryHeader(category ? 'btn-primary' : '');
    };

      
    const fetchCategories = async () => {
        try {
            let response = await category.getAll();
            setCategories(response.category || []);
        } catch(exception){
            console.log(exception);
        }
    };
    
    const fetchExpenses = async () => {
        try {
            let response = await expense.getAll();
            setRows(response.expense || []);
        } catch(exception){
            console.log(exception);
        }
    };
    
    const updateExpense = async (index) => {
        let response = await expense.update(rows[index].id, rows[index]);
        console.log(response);
    };
    
    const deleteConfirmation = (index) => {
        setSelectedExpenseIndex(index);
        setDeleteBodyMessage(`Are you sure you want to delete ${rows[index].expenses}?`);
        confirmationModal.show();
    };
      
    const deleteExpense = async () => {
        let index = selectedExpenseIndex;
        let response = await expense.delete(rows[index].id);
        if(response.success){
            setRows(rows.filter((_, i) => i !== index));
            confirmationModal.hide();
        }
    };
    
    const inputToggle = () => {
        setShowInput(!showInput);
    };

    const conditionalLayoutGrid = `${windowWidth > 600? 'w-layout-grid' : ''} uui-table_row new-row`;

    function FrequencyDropdownHeader({ options, selectedOption, selectOption }) {
        const [isOpen, setIsOpen] = useState(false);
    
        const handleToggle = () => {
            setIsOpen(!isOpen);
        };
    
        return (
            <div className={`dropdown dropdown-border ${isOpen ? 'show' : ''}`} onClick={handleToggle}>
                <button className={`btn frequency-width dropdown-toggle ${selectedOption["class"]}`} type="button">
                    {selectedOption.text}
                </button>
                <span className="dropdown-icon">▼</span>
                {isOpen && (
                    <ul className={`dropdown-menu ${isOpen ? 'show' : ''}`}>
                        {options.map((option) => (
                            <li key={option.text}>
                                <a className={`dropdown-item ${option["class"]}`} onClick={() => { selectOption(option); setIsOpen(false); }}>{option.text}</a>
                            </li>
                        ))}
                    </ul>
                )}
            </div>
        );
    }
    
    function CategoryDropdownHeader({ categories, selectedOption, selectOption }) {
        const [isOpen, setIsOpen] = useState(false);
    
        const handleToggle = () => {
            setIsOpen(!isOpen);
        };
    
        return (
            <div className={`dropdown dropdown-border ${isOpen ? 'show' : ''}`} onClick={handleToggle}>
                <button className={`btn dropdown-toggle frequency-width ${selectedOption ? 'btn-primary' : ''}`} type="button">
                    {selectedOption?.category_name || 'Select Category'}
                </button>
                <span className="dropdown-icon">▼</span>
                {isOpen && (
                    <ul className={`dropdown-menu ${isOpen ? 'show' : ''}`}>
                        <li>
                            <a className="dropdown-item" onClick={() => { selectOption(null); setIsOpen(false); }}>Select Category</a>
                        </li>
                        {categories.map((category) => (
                            <li key={category.id}>
                                <a className="dropdown-item one-time-expense frequency-width" onClick={() => { selectOption(category); setIsOpen(false); }}>{category.category_name}</a>
                            </li>
                        ))}
                    </ul>
                )}
            </div>
        );
    }
    
    function HeaderRow({ options, categories, selectOptionHeader, selectCategoryOptionHeader }) {
        const [headerExpense, setHeaderExpense] = useState(sessionStorage.getItem('headerExpense') ||  "");
        const [headerAmount, setHeaderAmount] = useState(sessionStorage.getItem('headerAmount') || 0);
        const [headerDate, setHeaderDate] = useState(sessionStorage.getItem('headerDate') || new Date());
        useEffect(() => {
            sessionStorage.setItem('headerExpense', headerExpense);
            sessionStorage.setItem('headerAmount', headerAmount);
            sessionStorage.setItem('headerDate', headerDate);
        }, [headerExpense, headerAmount, headerDate]); 
        const createExpense = async () => {
            if (headerExpense) {
              let body = {
                expenses: headerExpense,
                amount: headerAmount,
                start_date: headerDate,
                frequency: options.findIndex(x => selectedClassHeader === x["class"]),
                category: selectedOptionCategoryHeader.id
              };
              try {
                let response = await expense.create(body);
                if (response.success) {
                  setRows([...rows, response.expense]);
                  setHeaderExpense("");
                  setHeaderAmount(0);
                  setHeaderDate(new Date());
                  selectOptionHeader('Select Interval');
                  selectCategoryHeader({ category_name: 'Select Category' });
                  sessionStorage.removeItem('headerExpense');
                  sessionStorage.removeItem('headerAmount');
                  sessionStorage.removeItem('headerDate');
                } else {
                  console.error(response.message);
                }
              } catch (exception) {
                console.error(exception);
              }
            } else {
              console.warn("Please enter a category name");
            }
        };

        return (
            <div className={conditionalLayoutGrid}>

                <div className="uui-table_feature input-header">
                    <input type="text" className="expense-input" value={headerExpense} onChange={e => {
                        setHeaderExpense(e.target.value);
                    }} />
                </div>
                <div className="uui-table_row-content input-header">
                    <div className="expense-input">
                        <span className="input-group-addon">$</span>
                        <input type="number" className="no-border-input" value={headerAmount} onChange={e =>{ 
                                setHeaderAmount(e.target.value);
                            }
                        } />
                    </div>
                </div>
                <div className="uui-table_row-content input-header">
                    <input type="date" pattern="\d{4}-\d{2}-\d{2}" className="expense-input" value={headerDate} onChange={e => {
                        setHeaderDate(e.target.value);
                    }} />
                </div>
                <div className="uui-table_row-content input-header">
                    <FrequencyDropdownHeader options={options} selectedOption={options.find(option => option.text === selectedOptionHeader) || {"text": "Select Interval", "class": ""}} selectOption={selectOptionHeader} />
                </div>
                <div className="uui-table_row-content input-header">
                    <CategoryDropdownHeader categories={categories} selectedOption={categories.find(category => category.category_name === selectedOptionCategoryHeader.category_name)} selectOption={selectCategoryOptionHeader} />
                </div>
                <div className="uui-table_row-content input-header">
                    <button type="button" className="btn btn-primary add-button" onClick={createExpense}>Add</button>
                </div>
            </div>
        );
    }

    function FrequencyDropdown({ options, row, index, selectOption }) {
        const [isOpen, setIsOpen] = useState(false);
    
        const handleToggle = () => {
            setIsOpen(!isOpen);
        };
    
        return (
            <div className={`dropdown dropdown-border ${isOpen ? 'show' : ''}`} onClick={handleToggle}>
                <button className={`btn frequency-width dropdown-toggle ${isNaN(row.frequency) ? '' : options[row.frequency]["class"]}`} type="button">
                    {isNaN(row.frequency) ? 'Select Frequency' : options[row.frequency].text}
                </button>
                <span className="dropdown-icon">▼</span>
                {isOpen && (
                    <ul className={`dropdown-menu ${isOpen ? 'show' : ''}`}>
                        {options.map((option) => (
                            <li key={option.text}>
                                <a className={`dropdown-item ${option["class"]}`} onClick={() => { selectOption(option, index); setIsOpen(false); }}>{option.text}</a>
                            </li>
                        ))}
                    </ul>
                )}
            </div>
        );
    }
    
    function CategoryDropdown({ categories, row, index, selectCategoryOption }) {
        const [isOpen, setIsOpen] = useState(false);
    
        const handleToggle = () => {
            setIsOpen(!isOpen);
        };
    
        const selectedCategory = categories.find(category => category.id === row.category);
    
        return (
            <div className={`dropdown dropdown-border ${isOpen ? 'show' : ''}`} onClick={handleToggle}>
                <button className={`btn dropdown-toggle frequency-width ${selectedCategory ? 'btn-primary' : ''}`} type="button">
                    {selectedCategory?.category_name || 'Select Category'}
                </button>
                <span className="dropdown-icon">▼</span>
                {isOpen && (
                    <ul className={`dropdown-menu ${isOpen ? 'show' : ''}`}>
                        <li>
                            <a className="dropdown-item" onClick={() => { selectCategoryOption(null, index); setIsOpen(false); }}>Select Category</a>
                        </li>
                        {categories.map((category) => (
                            <li key={category.id}>
                                <a className="dropdown-item one-time-expense frequency-width" onClick={() => { selectCategoryOption(category, index); setIsOpen(false); }}>{category.category_name}</a>
                            </li>
                        ))}
                    </ul>
                )}
            </div>
        );
    }
    
    function Row({ row, index, options, categories, selectOption, selectCategoryOption, updateExpense, deleteConfirmation }) {
        const [expenses, setExpenses] = useState(sessionStorage.getItem(`expenses-${index}`) || row.expenses);
        const [amount, setAmount] = useState(sessionStorage.getItem(`amount-${index}`) || row.amount);
        const [startDate, setStartDate] = useState(sessionStorage.getItem(`start_date-${index}`) || row.start_date);

        useEffect(() => {
            sessionStorage.setItem(`expenses-${index}`, expenses);
            sessionStorage.setItem(`amount-${index}`, amount);
            sessionStorage.setItem(`start_date-${index}`, startDate);
        }, [expenses, amount, startDate]); 
        return (
            <div className={`w-layout-grid uui-table_row ${index % 2 === 1 ? 'background-color-gray50' : ''}`}>
                <div className="uui-table_feature">
                    <input type="text" className="expense-input" value={expenses} onChange={e => setExpenses(e.target.value)} />
                </div>
                <div className="uui-table_row-content">
                    <div className="expense-input">
                        <span className="input-group-addon">$</span>
                        <input type="number" className="no-border-input" value={amount} onChange={e => setAmount(e.target.value)} />
                    </div>
                </div>
                <div className="uui-table_row-content">
                    <input type="date" pattern="\d{4}-\d{2}-\d{2}" className="expense-input" value={startDate} onChange={e => setStartDate(e.target.value)} />
                </div>
                <div className="uui-table_row-content">
                    <FrequencyDropdown options={options} row={row} index={index} selectOption={selectOption} />
                </div>
                <div className="uui-table_row-content">
                    <CategoryDropdown categories={categories} row={row} index={index} selectCategoryOption={selectCategoryOption} />
                </div>
                <div className="uui-table_row-content">
                    <div className="action">
                        <button type="button" className="btn btn-warning" onClick={() => {
                            rows[index].expenses = expenses;
                            rows[index].amount = amount;
                            rows[index].start_date = startDate;
                            sessionStorage.removeItem(`expenses-${index}`);
                            sessionStorage.removeItem(`amount-${index}`);
                            sessionStorage.removeItem(`start_date-${index}`);
                            updateExpense(index);
                        }}>Save</button>
                        <button type="button" className="btn btn-danger" onClick={() => deleteConfirmation(index)}>Delete</button>
                    </div>
                </div>
            </div>
        );
    }
    
    return (
        <div class="uui-page-padding">
            <div class="uui-container-large">
                <div class="uui-padding-vertical-xhuge">
                    <div class="uui-text-align-center">
                        <div className="uui-max-width-large align-center">
                            <h2 className="uui-heading-medium">Expenses</h2>
                            <div className="uui-space-xsmall"></div>
                            <div className="uui-text-size-large">Add and manage your repeating <strong>expenses</strong></div>
                            <a href="#" className="button w-button" onClick={inputToggle}>{showInput ? "-" : "+"}</a>
                        </div>
                        {showInput && (
                                <HeaderRow
                                    options={options}
                                    categories={categories}
                                    selectOptionHeader={selectOptionHeader}
                                    selectCategoryOptionHeader={selectCategoryHeader}
                                />
                            )}
                    </div>
                    <div class="uui-table">
                        <div class="uui-table_heading-row">
                            <div class="uui-table_heading-row-text">Expense</div>
                            <div class="uui-table_heading-row-text">Amount</div>
                            <div class="uui-table_heading-row-text">Start Date</div>
                            <div class="uui-table_heading-row-text">Frequency</div>
                            <div class="uui-table_heading-row-text">Category</div>
                            <div class="uui-table_heading-row-text">Action</div>
                        </div>    
                    </div>
                    {rows.map((row, index) => (
                        <Row 
                            key={index} 
                            row={row} 
                            index={index} 
                            options={options} 
                            categories={categories} 
                            selectOption={selectOption} 
                            selectCategoryOption={selectCategoryOption} 
                            updateExpense={updateExpense} 
                            deleteConfirmation={deleteConfirmation} 
                        />
                    ))}

                </div>  
            </div>
            <ConfirmationModal 
                ref={confirmationModalRef}
                headerMessage="Delete Expense"
                bodyMessage={deleteBodyMessage}
                confirmationAction={deleteExpense}
                actionMessage="Delete"
                actionClass="btn-danger"
            />
        </div>
    );
}

export default Expenses;
