// plan-wise-angular-java/frontend/src/app/pages/budget-table/budget-table.component.ts
import { Component, OnInit, ViewChild, HostListener } from '@angular/core';
import { AccountService } from '../../../services/account.service';
import { BudgetTableService } from '../../../services/budget-table.service';
import { NoteService } from '../../../services/notes.service';
import { NotesModalComponent } from '../../components/notes-modal/notes-modal.component';
import { ExpenseModalComponent } from '../../components/expense-modal/expense-modal.component';
import { IncomeModalComponent } from '../../components/income-modal/income-modal.component';
import { ModifyInstanceModalComponent } from '../../components/modify-instance-modal/modify-instance-modal.component';
import * as moment from 'moment';

@Component({
  selector: 'app-budget-table',
  templateUrl: './budget-table.component.html',
  styleUrls: ['./budget-table.component.css', '../../../assets/components.css', '../../../assets/budgeting-app.css']
})
export class BudgetTableComponent implements OnInit {
  currMonth = -1;
  currYear = -1;
  initialBalance: any = 0;
  monthDailyData: any = {};
  selectedDate = new Date().toISOString();
  balanceHistory: any = [];
  months = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December'
  ];
  calendar: any = [];
  mediaQuery = window.matchMedia("(min-width: 724px)");
  isLargeScreen = this.mediaQuery.matches;
  currentNotes = {
    notes: ""
  };

  selectedOptionCategoryHeader: any = "";
  selectedClassCategoryHeader = "";
  selectedOptionHeader = "";
  selectedClassHeader = "";
  selectedOption = "";
  selectedClass = "";
  headerExpense = "";
  headerSource = "";
  headerAmount = 0;
  headerDate = "";
  selectedInstance = {
    expense: [],
    income: []
  };

  @ViewChild('noteModal') noteModal!: NotesModalComponent;
  @ViewChild('expenseModal') expenseModal!: ExpenseModalComponent;
  @ViewChild('incomeModal') incomeModal!: IncomeModalComponent;
  @ViewChild('modifyInstanceModal') modifyInstanceModal!: ModifyInstanceModalComponent;

  constructor(private accountAPI: AccountService, private budgetTableAPI: BudgetTableService, private notesAPI: NoteService) { }

  ngOnInit(): void {
    document.title = "Plan Wise - Budget Table";
    this.initializeData();
  }

  async initializeData() {
    const user: any = (await this.accountAPI.getUser());
    this.initialBalance = user?.balance || 0;
    const monthDailyData: any = (await this.budgetTableAPI.getBudgetsInDateRange(undefined));
    const currMonth = moment(Object.keys(monthDailyData.budgets)[0]).month();
    const currYear = moment(Object.keys(monthDailyData.budgets)[0]).year();
    this.currMonth = currMonth;
    this.currYear = currYear;
    const calendar = this.getDaysInMonth(new Date(currYear, currMonth, 1), new Date(currYear, currMonth + 1, 0));
    this.calendar = calendar;
    await this.generate(monthDailyData.budgets, user?.user.balance || 0);
  }

  async generate(monthDailyData: any, initialBalance: any) {
    let prevKey = Object.keys(monthDailyData)[0];
    for (let key of Object.keys(monthDailyData)) {
      const income = monthDailyData[key].income.reduce((total: any, current: any) => total + current.amount, 0);
      const expense = monthDailyData[key].expense.reduce((total: any, current: any) => total + current.amount, 0);
      const currentBalance = (monthDailyData[prevKey].currentBalance || initialBalance) + income - expense;
      monthDailyData[key].previousBalance = monthDailyData[prevKey].currentBalance ? monthDailyData[prevKey].currentBalance : initialBalance;
      monthDailyData[key].currentBalance = currentBalance;
      prevKey = key;
    }
    this.monthDailyData = monthDailyData;
  }

  async incrementMonth() {
    const monthData = Object.keys(this.monthDailyData);
    const newMonth = moment(monthData[0]).add(1, 'M').month();
    const newYear = moment(monthData[0]).add(1, 'M').year();
    this.currMonth = newMonth;
    this.currYear = newYear;
    this.balanceHistory.push(this.initialBalance);
    this.balanceHistory = this.balanceHistory;
    const calendar = this.getDaysInMonth(new Date(newYear, newMonth, 1), new Date(newYear, newMonth + 1, 0));
    this.calendar = calendar;
    const newInitialBalance = this.monthDailyData[monthData[monthData.length - 1]].currentBalance;
    this.initialBalance = newInitialBalance;
    const newCurrentBalance = newInitialBalance;
    this.initialBalance = newCurrentBalance;
    await this.getMonthlyData(newMonth, newYear, newInitialBalance);
    this.calendar = calendar;
  }
  

  async decrementMonth() {
    const monthData = Object.keys(this.monthDailyData);
    const newMonth = moment(monthData[0]).subtract(1, 'M').month();
    const newYear = moment(monthData[0]).subtract(1, 'M').year();
    let newInitialBalance: any = 0;
    this.currMonth = newMonth;
    this.currYear = newYear;
    const calendar = this.getDaysInMonth(new Date(newYear, newMonth, 1), new Date(newYear, newMonth + 1, 0));
    this.calendar = calendar;
    if (this.balanceHistory.length > 0) {
      newInitialBalance = this.balanceHistory.pop();
      this.initialBalance = newInitialBalance;
    }
    this.initialBalance = newInitialBalance;
    this.calendar = calendar;
    await this.getMonthlyData(newMonth, newYear, newInitialBalance);
  }
  
  getDaysInMonth(start: any, end: any) {
    const dates = [];
    let current = new Date(start);
    let index = 1;
    while (current <= end) {
      dates.push({
        date: moment(current).format('YYYY-MM-DD').toString(),
        dayOfWeek: current.getDay(),
        index: index
      });
      current.setDate(current.getDate() + 1);
      current = new Date(current);
      index++;
    }
    return dates;
  }
  
  async changeInitialBalance() {
    await this.accountAPI.updateUser({
      balance: this.initialBalance
    });
    await this.initializeData();
  }
  
  addIncomeModal(date: any) {
    this.selectedDate = date;
    this.headerDate = date;
    this.selectedOptionHeader = 'Select Interval';
    this.selectedClassHeader = '';
    this.selectedOption = 'Select Interval';
    this.selectedClass = '';
    this.headerSource = '';
    this.headerAmount = 0;
    this.incomeModal.open();
  }
  
  addExpenseModal(date: any) {
    this.selectedDate = date;
    this.headerDate = date;
    this.selectedOptionCategoryHeader = { category_name: 'Select Category' };
    this.selectedClassCategoryHeader = '';
    this.selectedOptionHeader = 'Select Interval';
    this.selectedClassHeader = '';
    this.selectedOption = 'Select Interval';
    this.selectedClass = '';
    this.headerExpense = '';
    this.headerAmount = 0;
    this.expenseModal.open();
  }
  
  selectedInstanceModal(date: any) {
    this.selectedDate = date;
    this.selectedInstance = this.monthDailyData[date];
    this.modifyInstanceModal.open();
  }
  
  async notesModal(date: any) {
    try {
      let noteResponse: any = await this.notesAPI.getByDate(date);
      this.currentNotes = noteResponse.notes[0] || {
        notes: ""
      };
      this.selectedDate = date;
      this.noteModal.open(this.currentNotes, this.selectedDate);
    } catch(e) {
      this.currentNotes = {
        notes: ""
      };
      this.selectedDate = date;
      this.noteModal.open(this.currentNotes, this.selectedDate);
    }
  }
  
  async refreshTable() {
    const month = moment(this.selectedDate).month();
    const year = moment(this.selectedDate).year();
    const calendar = this.getDaysInMonth(new Date(year, month, 1), new Date(year, month + 1, 0));
    this.calendar = calendar;
    const initBalance = this.monthDailyData[this.selectedDate].previousBalance;
    this.initialBalance = initBalance;
    await this.getMonthlyData(month, year, initBalance);
    this.calendar = calendar;
    this.expenseModal.close();
    this.incomeModal.close();
    this.modifyInstanceModal.close();
  }
  async getMonthlyData(month: any, year: any, initialBalance: any) {
    console.log(initialBalance);
    this.currMonth = month;
    this.currYear = year;
    console.log(new Date(year, month, 1));
    const result: any = await this.budgetTableAPI.getBudgetsInDateRange(moment(new Date(year, month, 1)).format("YYYY-MM-DD"));
    const monthDailyData = result.budgets || {};
    this.monthDailyData = monthDailyData;
    let prevKey = Object.keys(monthDailyData)[0];
    for (let key of Object.keys(monthDailyData)) {
      const income = monthDailyData[key].income.reduce((total: any, current: any) => total + current.amount, 0);
      const expense = monthDailyData[key].expense.reduce((total: any, current: any) => total + current.amount, 0);
      const currentBalance = (monthDailyData[prevKey].currentBalance || initialBalance) + income - expense;
      monthDailyData[key].previousBalance = monthDailyData[prevKey].currentBalance ? monthDailyData[prevKey].currentBalance : initialBalance;
      monthDailyData[key].currentBalance = currentBalance;
      prevKey = key;
    }
    this.monthDailyData = monthDailyData;
    const calendar = this.getDaysInMonth(new Date(year, month, 1), new Date(year, month + 1, 0));
    this.calendar = calendar;
  }
  
  @HostListener('window:resize', ['$event'])
  onResize(event: any) {
    this.updateMediaQuery(event);
  }
  
  updateMediaQuery(event: any) {
    this.mediaQuery = event.target;
    this.isLargeScreen = window.matchMedia("(min-width: 724px)").matches;
  }

  getBalanceDisplay(balance: number): string {
    if (balance > 0) {
      return `$${balance.toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
    } else if (!isNaN(balance)) {
      return `-$${Math.abs(balance).toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
    } else {
      return '';
    }
  }

  getIncomeDisplay(income: any[]): string {
    if (income.length > 0) {
      const totalIncome = income.reduce((total, current) => total + current.amount, 0);
      return `$${totalIncome.toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
    } else {
      return '';
    }
  }

  getArray(length: number): any[] {
    return Array(length);
  }

}

<section class="uui-section_table">
    <div class="uui-page-padding">
      <div class="uui-container-large">
        <div class="uui-padding-vertical-xhuge">
            <div class="uui-text-align-center">
                <div class="uui-max-width-large align-center">
                <h2 class="uui-heading-medium">Budget Table</h2>
                <div class="uui-space-xsmall"></div>
                <div class="uui-text-size-large">See where you&#x27;ll be if you stick to your budget<strong></strong></div>
                </div>
            </div>
                <div class="uui-table">
                    <div class="">
                        <div [ngClass]="{'w-layout-grid': isLargeScreen, 'uui-table_row': true, 'new-row': true}">
                            <div class="uui-table_row-content input-header">
                              <span>Initial Balance:</span>
                            </div>
                            <div class="uui-table_row-content input-header">
                              <input type="number" class="expense-input" [(ngModel)]="initialBalance" />
                            </div>
                            <div class="uui-table_row-content input-header">
                              <button type="button" class="btn btn-primary" (click)="changeInitialBalance()">Change</button>
                            </div>
                        </div>                          
                        <div class="uui-table_heading-row">
                          <div class="uui-table_heading-row-text">Date</div>
                          <div class="uui-table_heading-row-text">Balance</div>
                          <div class="uui-table_heading-row-text">Income</div>
                          <div class="uui-table_heading-row-text">Expense</div>
                          <div class="uui-table_heading-row-text">Amount</div>
                          <div class="uui-table_heading-row-text">Action</div>
                        </div>
                        <div class="div-block">
                          <ul class="pagination">
                            <li class="page-item">
                              <a class="text-block-3 page-link-budget" href="javascript:void(0)" (click)="decrementMonth()"><<</a>
                            </li>
                            <li>
                              <div class="text-block-3 px-2">{{months[currMonth]}} {{currYear < 0 ? '' : currYear}}</div>
                            </li>
                            <li class="page-item">
                              <a class="text-block-3 page-link-budget" href="javascript:void(0)" (click)="incrementMonth()">>></a>
                            </li>
                          </ul>
                        </div>
                    </div>
                      
                    <div *ngIf="isLargeScreen">
                        <div *ngFor="let dayData of calendar; index as i" class="w-layout-grid uui-table_row background-color-gray50">
                            <div class="w-layout-grid uui-table-row-day-of-month">
                                <div class="div-block-2">
                                <div class="uui-pricing07_row-lead-text date-column">{{dayData.date}}</div>
                                </div>
                            </div>

                            <div *ngIf="monthDailyData[dayData.date] && monthDailyData[dayData.date].previousBalance && monthDailyData[dayData.date].currentBalance" class="w-layout-grid uui-table-row-day-of-month balance-column">
                                <div class="uui-text-size-medium starting-balance">
                                {{ getBalanceDisplay(monthDailyData[dayData.date].previousBalance || 0) }}
                                </div>
                                <div class="uui-text-size-medium ending-balance">
                                {{ getBalanceDisplay(monthDailyData[dayData.date].currentBalance) }}
                                </div>
                            </div>
                            <div *ngIf="!monthDailyData[dayData.date] || !monthDailyData[dayData.date].previousBalance || !monthDailyData[dayData.date].currentBalance" class="w-layout-grid uui-table-row-day-of-month">
                                <div class="div-block-2"></div>
                            </div>
                            <div *ngIf="monthDailyData[dayData.date]" class="w-layout-grid uui-table-row-day-of-month income-column">
                                <div class="{{(monthDailyData[dayData.date].income || []).length > 0 ? 'uui-text-size-medium income' : 'uui-text-size-medium'}}">
                                {{ getIncomeDisplay(monthDailyData[dayData.date].income || []) }}
                                </div>
                                <div *ngFor="let _ of getArray((monthDailyData[dayData.date].expense || []).length - 1)" class="uui-text-size-medium">
                                    <div></div>
                                </div>                                  
                            </div>
                            <div *ngIf="!monthDailyData[dayData.date]" class="w-layout-grid uui-table-row-day-of-month">
                                <div class="div-block-2"></div>
                            </div>
                            <div *ngIf="monthDailyData[dayData.date]" class="w-layout-grid uui-table-row-day-of-month expense-column">
                                <div *ngFor="let expense of (monthDailyData[dayData.date].expense || [])" class="uui-text-size-medium expense-cell">{{expense.expenses}}</div>
                            </div>
                            <div *ngIf="!monthDailyData[dayData.date]" class="w-layout-grid uui-table-row-day-of-month">
                                <div class="div-block-2"></div>
                            </div>
                            <div *ngIf="monthDailyData[dayData.date]" class="w-layout-grid uui-table-row-day-of-month expense-price-column">
                                <div *ngFor="let expense of (monthDailyData[dayData.date].expense || [])" class="uui-text-size-medium expense-cell">
                                $ {{expense.amount.toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}}
                                </div>
                            </div>
                            <div *ngIf="!monthDailyData[dayData.date]" class="w-layout-grid uui-table-row-day-of-month">
                                <div class="div-block-2"></div>
                            </div>

                            <div class="w-layout-grid uui-table-row-day-of-month action-column">
                                <div class="action">
                                <div class="action-data">
                                    <button type="button" class="btn btn-primary" (click)="addIncomeModal(dayData.date)">Add Income</button>
                                    <button type="button" class="btn btn-primary" (click)="addExpenseModal(dayData.date)">Add Expense</button>
                                    <button type="button" class="btn btn-primary" [disabled]="!monthDailyData[dayData.date]" (click)="selectedInstanceModal(dayData.date)">Modify Instance</button>
                                    <button type="button" class="btn btn-primary" (click)="notesModal(dayData.date)">Notes</button>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                      
                    <div class="center-pagination">
                        <nav aria-label="Page navigation example">
                          <ul class="pagination">
                            <li class="page-item">
                              <a class="page-link" href="javascript:void(0)" (click)="decrementMonth()">Previous</a>
                            </li>
                            <li class="page-item">
                              <a class="page-link" href="javascript:void(0)" (click)="incrementMonth()">Next</a>
                            </li>
                          </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <app-notes-modal 
        #noteModal 
        (modalClosed)="refreshTable()" 
        [currentNotes]="currentNotes" 
        [selectedDate]="selectedDate">
    </app-notes-modal>
    <app-expense-modal
        #expenseModal
        (modalClosed)="refreshTable()"
        [selectedOptionCategoryHeader]="selectedOptionCategoryHeader"
        [selectedClassCategoryHeader]="selectedClassCategoryHeader"
        [selectedOptionHeader]="selectedOptionHeader"
        [selectedClassHeader]="selectedClassHeader"
        [headerExpense]="headerExpense"
        [headerAmount]="headerAmount"
        [headerDate]="headerDate"
        [selectedDate]="selectedDate">
    </app-expense-modal>
    <app-income-modal
        #incomeModal
        (modalClosed)="refreshTable()"
        [selectedOptionHeader]="selectedOptionHeader"
        [selectedClassHeader]="selectedClassHeader"
        [headerSource]="headerSource"
        [headerAmount]="headerAmount"
        [headerDate]="headerDate"
        [selectedDate]="selectedDate">
    </app-income-modal>
    <app-modify-instance-modal
        #modifyInstanceModal
        (modalClosed)="refreshTable()"
        [selectedDate]="selectedDate"
        [selectedInstance]="selectedInstance">
    </app-modify-instance-modal>
</section>

// frontend/src/pages/BudgetTable.vue
<template>

  <section class="uui-section_table">
    <div class="uui-page-padding">
      <div class="uui-container-large">
        <div class="uui-padding-vertical-xhuge">
          <div class="uui-text-align-center">
            <div class="uui-max-width-large align-center">
              <h2 class="uui-heading-medium">Budget Table</h2>
              <div class="uui-space-xsmall"></div>
              <div class="uui-text-size-large">See where you&#x27;ll be if you stick to your budget<strong></strong></div>
            </div>
          </div>
          <div class="uui-table">
            <div class="">
              <div :class="conditionalLayoutGrid">
                <div class="uui-table_row-content input-header">
                  <span>Initial Balance:</span>
                </div>
                <div class="uui-table_row-content input-header">
                  <input type="number" class="expense-input" v-model="initialBalance">
                </div>
                <div class="uui-table_row-content input-header">
                  <button type="button" class="btn btn-primary" @click="changeInitialBalance">Change</button>
                </div>
              </div>
              <div class="uui-table_heading-row">
                <div class="uui-table_heading-row-text">Date</div>
                <div class="uui-table_heading-row-text">Balance</div>
                <div class="uui-table_heading-row-text">Income</div>
                <div class="uui-table_heading-row-text">Expense</div>
                <div class="uui-table_heading-row-text">Amount</div>
                <div class="uui-table_heading-row-text">Action</div>
              </div>
              <div class="div-block">
                <ul class="pagination">
                  <li class="page-item">
                    <a class="text-block-3 page-link-budget" href="#" @click="decrementMonth">&lt;&lt;</a>
                  </li>
                  <li>
                    <div class="text-block-3 px-2">{{ months[currMonth] }} {{currYear < 0? '' : currYear}}</div>
                  </li>
                  <li class="page-item">
                    <a class="text-block-3 page-link-budget" href="#" @click="incrementMonth">&gt;&gt;</a>
                  </li>
                </ul>
              </div>
            </div>
            <div v-if="isLargeScreen">
              <div v-for="dayData in calendar" :key="dayData.index" class="w-layout-grid uui-table_row background-color-gray50">
                  <div class="w-layout-grid uui-table-row-day-of-month">
                    <div class="div-block-2">
                        <div class="uui-pricing07_row-lead-text date-column">{{ dayData.date }}</div>
                    </div>
                  </div>
                  <div v-if="monthDailyData[dayData.date] && monthDailyData[dayData.date].previousBalance && monthDailyData[dayData.date].currentBalance" class="w-layout-grid uui-table-row-day-of-month balance-column">
                    <div class="uui-text-size-medium starting-balance">
                      {{ ((monthDailyData[dayData.date].previousBalance || 0) > 0? 
                          `$${monthDailyData[dayData.date].previousBalance.toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : 
                            !isNaN(monthDailyData[dayData.date].previousBalance)? 
                              `-$${Math.abs(monthDailyData[dayData.date].previousBalance).toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : '')
                              
                      }}
                    </div>
                    <div class="uui-text-size-medium ending-balance">
                      {{ 
                        (monthDailyData[dayData.date].currentBalance > 0? 
                          `$${monthDailyData[dayData.date].currentBalance
                            .toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : 
                            `-$${Math.abs(monthDailyData[dayData.date].currentBalance)
                              .toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}`)
                      }}</div>
                  </div>
                  <div v-else class="w-layout-grid uui-table-row-day-of-month">
                    <div class="div-block-2"></div>
                  </div>

                  <div v-if="monthDailyData[dayData.date]" class="w-layout-grid uui-table-row-day-of-month income-column">
                    <div v-bind:class="(monthDailyData[dayData.date].income  || []).length > 0 ? 'uui-text-size-medium income' : 'uui-text-size-medium'">
                      {{ 
                        ((monthDailyData[dayData.date].income  || []).length > 0 ? `$${(monthDailyData[dayData.date].income  || [])
                          .reduce((total, current) => total + current.amount, 0)
                          .toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : '' )
                      }}</div>
                    <div v-for="i in Math.max((monthDailyData[dayData.date].expense || []).length - 1, 0)" :key="i" class="uui-text-size-medium">
                      <div v-if="i > (monthDailyData[dayData.date].income  || []).length"></div>
                    </div>
                  </div>
                  <div v-else class="w-layout-grid uui-table-row-day-of-month">
                    <div class="div-block-2"></div>
                  </div>
                  <div v-if="monthDailyData[dayData.date]" class="w-layout-grid uui-table-row-day-of-month expense-column">
                    <div v-for="(expense, index) in (monthDailyData[dayData.date].expense || [])" :key="index" class="uui-text-size-medium expense-cell">{{ expense.expenses }}</div>
                  </div>
                  <div v-else class="w-layout-grid uui-table-row-day-of-month">
                    <div class="div-block-2"></div>
                  </div>
                  <div v-if="monthDailyData[dayData.date]" class="w-layout-grid uui-table-row-day-of-month expense-price-column">
                    <div v-for="(expense, index) in (monthDailyData[dayData.date].expense || [])" :key="index" class="uui-text-size-medium expense-cell">
                      $ {{ 
                        expense.amount.toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 }) 
                      }}</div>
                </div>
                  <div v-else class="w-layout-grid uui-table-row-day-of-month">
                    <div class="div-block-2"></div>
                  </div>

                <div class="w-layout-grid uui-table-row-day-of-month action-column">
                  <div class="action">
                    <div class="action-data">
                      <button type="button" class="btn btn-primary" @click="addIncomeModal(dayData.date)">Add Income</button>
                      <button type="button" class="btn btn-primary" @click="addExpenseModal(dayData.date)">Add Expense</button>
                      <button type="button" class="btn btn-primary" :disabled="!monthDailyData[dayData.date]" @click="selectedInstanceModal(dayData.date)">Modify Instance</button>
                      <button type="button" class="btn btn-primary" @click="notesModal(dayData.date)">Notes</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div v-if="!isLargeScreen">
              <div v-for="dayData in calendar" :key="dayData.index" class="w-layout-grid-calendar-mobile background-color-gray50 calendar-mobile">
                <div v-if="dayData.date" class="uui-table_row_mobile">
                  <div class="w-layout-grid uui-table-row-day-of-month_mobile">
                    <div class="div-block-3">
                        <div class="uui-pricing07_row-lead-text date-column">{{ dayData.date }}</div>
                        <div class="uui-pricing07_row-lead-text date-column">{{ daysOfWeek[dayData.dayOfWeek] }}</div>
                    </div>
                    <div class="w-layout-grid uui-table-row-day-of-month">
                      <div :class="'uui-text-size-medium ' + getBalanceClass(dayData.date, 'starting', 'previousBalance')">
                        {{  
                          monthDailyData[dayData.date]?.previousBalance? 
                            "Start Bal: " + (monthDailyData[dayData.date]?.previousBalance > 0? 
                              `$${monthDailyData[dayData.date]?.previousBalance.toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 }) }` : 
                              `-$${Math.abs(monthDailyData[dayData.date]?.previousBalance).toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 }) }`) : 
                              '-' 
                        }}
                      </div>
                      <div :class="'uui-text-size-medium ' + (totalIncome(dayData.date) > 0? 'income' : 'hide-dash')">
                        {{ monthDailyData[dayData.date]?.income.length > 0?  "Income: $" + totalIncome(dayData.date).toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 }) : '-' }}
                      </div>
                      <div :class="'uui-text-size-medium ' + (totalExpense(dayData.date) > 0? 'expense' : 'hide-dash')">
                        {{  monthDailyData[dayData.date]?.expense.length > 0? "Expense: $" + totalExpense(dayData.date).toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 }) : '-' }}
                      </div>
                      <div :class="'uui-text-size-medium ' + getBalanceClass(dayData.date, 'ending', 'currentBalance')">
                        {{
                            monthDailyData[dayData.date]?.currentBalance?
                              "End Bal: " + (monthDailyData[dayData.date].currentBalance > 0? 
                                `$${monthDailyData[dayData.date].currentBalance.toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 }) }` : 
                                `-$${Math.abs(monthDailyData[dayData.date].currentBalance).toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 }) }`) : '-' 
                        }}
                      </div>
                    </div>
                  </div>
                </div>
                      <div class="action">
                        <div class="action-data">
                          <button type="button" class="btn btn-primary" @click="addIncomeModal(dayData.date)">Add Income</button>
                          <button type="button" class="btn btn-primary" @click="addExpenseModal(dayData.date)">Add Expense</button>
                          <button type="button" class="btn btn-primary" :disabled="!monthDailyData[dayData.date]" @click="selectedInstanceModal(dayData.date)">Modify Instance</button>
                          <button type="button" class="btn btn-primary" @click="notesModal(dayData.date)">Notes</button>
                        </div>
                      </div>
              </div>
            </div>
            <div class="center-pagination">
              <nav aria-label="Page navigation example">
                <ul class="pagination">
                  <li class="page-item">
                    <a class="page-link" href="#" @click="decrementMonth">&lt;&lt; Previous</a>
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="#" @click="incrementMonth">Next &gt;&gt;</a>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>

    <income-modal 
      ref="incomeModal"
      @modal-closed="refreshTable"
      :selected-option-category-header="selectedOptionCategoryHeader"
      :selected-class-category-header="selectedClassCategoryHeader"
      :selected-option-header="selectedOptionHeader"
      :selected-class-header="selectedClassHeader"
      :selected-option="selectedOption"
      :selected-class="selectedClass"
      :header-source="headerSource"
      :header-amount="headerAmount"
      :header-date="headerDate"
      :selected-date="selectedDate">
    </income-modal>

    <expense-modal 
      ref="expenseModal"
      @modal-closed="refreshTable"
      :selected-option-category-header="selectedOptionCategoryHeader"
      :selected-class-category-header="selectedClassCategoryHeader"
      :selected-option-header="selectedOptionHeader"
      :selected-class-header="selectedClassHeader"
      :selected-option="selectedOption"
      :selected-class="selectedClass"
      :header-source="headerExpense"
      :header-amount="headerAmount"
      :header-date="headerDate"
      :selected-date="selectedDate">
    </expense-modal>

    <modify-instance-modal
      ref="modifyInstanceModal"
      @modal-closed="refreshTable"
      :selected-instance="selectedInstance"
      :selected-date="selectedDate"
    >
    </modify-instance-modal>

    <notes-modal
      ref="noteModal"
      @modal-closed="refreshTable"
      :current-notes="currentNotes"
      :selected-date="selectedDate"
    >
    </notes-modal>
  </section>
</template>
  
<style scoped>
@import '../assets/components.css';
@import '../assets/budgeting-app.css';
.center-pagination{
  width: 100%;
  padding: 50px;
}
.center-pagination > nav{
  margin: auto;
}
.expense-input{
  width: 100%;
  padding: 5px;
  border-radius: 5px;
  border: 1px solid rgba(0, 0, 0, .1);
  background: transparent;
  font-family: system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Noto Sans,Ubuntu,Cantarell,Helvetica Neue,Oxygen,Fira Sans,Droid Sans,sans-serif;
    font-size: 1.125rem;
}

.modal-input {
  width: 50% !important;
}
.page-link-budget{
  background-color: transparent;
  border: none;
  color: white;
  text-decoration: none;
}
.action{
  padding-left: 10px;
  padding-right: 10px;
}
.action-data{
  display: flex;
  flex-direction: column;
  row-gap: 10px;
}
.expense-cell {
  padding: 15px !important;
}
.income-expense-input{
  display: flex;
  flex-direction: column;
  row-gap: 15px;
}
.income-expense-row{
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}
.dropdown-menu{
  padding-left: 10px !important;
  padding-right: 10px !important;
}
.dropdown-icon {
  position: absolute;
  right: 10px;
  top: 50%;
  transform: translateY(-50%);
}
.btn.dropdown-toggle::after {
  display: none;
}

.hide-dash{
  color: transparent;
}
#instanceTabs {
  padding-left: 0px !important;
}
</style>

<script>
import accountAPI from '../services/account-service';
import budgetTableAPI from '../services/budget-table-service';
import notesAPI from '../services/notes-service';
import IncomeModal from '../components/IncomeModal.vue';
import ExpenseModal from '../components/ExpenseModal.vue';
import mixin from '../utils/mixin';
import moment from 'moment';
import { Modal } from 'bootstrap';
import ModifyInstanceModal from '../components/ModifyInstanceModal.vue';
import NotesModal from '../components/NotesModal.vue';

export default {
  components: { IncomeModal, ExpenseModal, ModifyInstanceModal, NotesModal },
  mixins: [mixin],
  data() {
      return {
        currMonth: -1,
        currYear: -1,
        currentNotes: {
          notes: ""
        },
        total: 365,
        initialBalance: 0,
        currentBalance: 0,
        balanceHistory: [],
        monthDailyData: {},
        selectedDate: "",
        monthlyBalances: {},
        calendar: [],
        months: [
          'January',
          'February',
          'March',
          'April',
          'May',
          'June',
          'July',
          'August',
          'September',
          'October',
          'November',
          'December'
        ],
        noteModal: null,
        incomeModal: null,
        expenseModal: null,
        modifyInstanceModal: null,
        expenseInstanceIndex: 0,
        incomeInstanceIndex: 0,
        selectedInstance: {
          expense: [],
          income: []
        },
        origSelectedIntance: {
          expense: [],
          income: []
        },
        mediaQuery: window.matchMedia("(min-width: 724px)"),
        daysOfWeek: [
          "Sunday",
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday",
          "Saturday",
        ],
      }
    },
    mounted() {
      document.title = "Plan Wise - Budget Table";
      this.initializeData();
      this.noteModal = new Modal(this.$refs.noteModal.$el);
      this.incomeModal = new Modal(this.$refs.incomeModal.$el);
      this.expenseModal = new Modal(this.$refs.expenseModal.$el);
      this.modifyInstanceModal = new Modal(this.$refs.modifyInstanceModal.$el);
      this.$refs.incomeModal.$el.addEventListener('shown.bs.modal', () => {
        this.$refs.incomeModal.onShow();
      });
      this.$refs.expenseModal.$el.addEventListener('shown.bs.modal', () => {
        this.$refs.expenseModal.onShow();
      });
      this.$refs.modifyInstanceModal.$el.addEventListener('shown.bs.modal', () => {
        this.$refs.modifyInstanceModal.onShow();
      });
      this.$refs.noteModal.$el.addEventListener('shown.bs.modal', () => {
        this.$refs.noteModal.onShow();
      });
    },
    methods: {
      generateDates(startDate, frequency, duration) {
          let dates = []
          let date = moment(startDate)
          while (date.diff(moment(startDate), 'days') <= duration) {
              dates.push(date.format('YYYY-MM-DD'))
              switch (frequency) {
                  case 0:
                      date.add(1, 'days')
                      break
                  case 1:
                      date.add(7, 'days')
                      break
                  case 2:
                      date.add(14, 'days')
                      break
                  case 3:
                      date.add(1, 'months')
                      break
                  case 4:
                      date.add(3, 'months')
                      break
                  case 5:
                      date.add(6, 'months')
                      break
                  case 6:
                      date.add(1, 'years')
                      break
                  default:
                    return dates;
              }
          }
          return dates;
      },
      getDaysInMonth(start, end) {
          const dates = [];
          let current = new Date(start);
          let index = 1;
          while (current <= end) {
              dates.push({
                date: moment(current).format('YYYY-MM-DD').toString(),
                dayOfWeek: current.getDay(),
                index: index
              });
              current.setDate(current.getDate() + 1);
              current = new Date(current);
              index++;
          }
          return dates;
      },
      getMonthlyData(month, year) {
          this.currMonth = month;
          this.currYear = year;
          budgetTableAPI.getBudgetsInDateRange(moment(new Date (this.currYear , this.currMonth, 1)).format("YYYY-MM-DD")).then(result => {
            this.monthDailyData = result.budgets || {};
            let prevKey = Object.keys(this.monthDailyData)[0];
            for (let key of Object.keys(this.monthDailyData)) {
              const income = this.monthDailyData[key].income.reduce((total, current) => total + current.amount, 0);
              const expense = this.monthDailyData[key].expense.reduce((total, current) => total + current.amount, 0);
              this.currentBalance += income - expense;
              this.monthDailyData[key].previousBalance = this.monthDailyData[prevKey].currentBalance? this.monthDailyData[prevKey].currentBalance : this.initialBalance;
              this.monthDailyData[key].currentBalance = this.currentBalance;
              prevKey = key;
            }
          });
      },
      changeMonth(direction) {
          if (direction == 'next') {
              this.incrementMonth()
          } else if (direction == 'prev') {
              this.decrementMonth() 
          }
      },
      incrementMonth() {
        const monthData = Object.keys(this.monthDailyData);
        this.currMonth = moment(monthData[0]).add(1, 'month').month();
        this.currYear = moment(monthData[0]).add(1, 'month').year();
        this.calendar = this.getDaysInMonth(new Date (this.currYear , this.currMonth, 1), new Date (this.currYear , this.currMonth + 1, 0));
        this.balanceHistory.push(this.initialBalance);
        this.initialBalance = this.monthDailyData[monthData[monthData.length - 1]].currentBalance;
        this.currentBalance = this.initialBalance;
        this.getMonthlyData(this.currMonth, this.currYear);
      },
      decrementMonth() {
        const monthData = Object.keys(this.monthDailyData);
        this.currMonth = moment(monthData[0]).subtract(1, 'month').month();
        this.currYear = moment(monthData[0]).subtract(1, 'month').year();
        this.calendar = this.getDaysInMonth(new Date (this.currYear , this.currMonth, 1), new Date (this.currYear , this.currMonth + 1, 0));
        if (this.balanceHistory.length > 0) {
          this.initialBalance = this.balanceHistory.pop();
        }
        this.currentBalance = this.initialBalance;
        this.getMonthlyData(this.currMonth, this.currYear);
      },
      getBalanceClass(date) {
        return this.monthlyBalances[date] < 0 ? 'expense' : this.monthlyBalances[date] > 0? 'starting-balance' : 'hide-dash';
      },
      refreshTable(){
        this.calendar = this.getDaysInMonth(new Date (this.currYear , this.currMonth, 1), new Date (this.currYear , this.currMonth + 1, 0));
        this.currentBalance = this.initialBalance;
        this.getMonthlyData(this.currMonth, this.currYear);
        this.incomeModal.hide();
        this.expenseModal.hide();
        this.modifyInstanceModal.hide();
        this.noteModal.hide();
      },
      addIncomeModal(date){
        this.selectedDate = date;
        this.selectedOptionCategoryHeader = { category_name: 'Select Category' };
        this.selectedClassCategoryHeader = '';
        this.selectedOptionHeader = 'Select Interval';
        this.selectedClassHeader = '';
        this.selectedOption = 'Select Interval';
        this.selectedClass = '';
        this.headerSource = '';
        this.headerAmount = 0;
        this.headerExpense = '';
        this.incomeModal.show();
      },
      addExpenseModal(date){
        this.selectedDate = date;
        this.selectedOptionCategoryHeader = { category_name: 'Select Category' };
        this.selectedClassCategoryHeader = '';
        this.selectedOptionHeader = 'Select Interval';
        this.selectedClassHeader = '';
        this.selectedOption = 'Select Interval';
        this.selectedClass = '';
        this.headerExpense = '';
        this.headerAmount = 0;
        this.expenseModal.show();
      },
      selectOptionInstance(type, index) {
        this.selectedInstance[type].frequency = index;
      },
      selectCategoryHeader(category) {
        this.selectedOptionCategoryHeader = category;
        this.selectedClassCategoryHeader = category.category_name === 'Select Category'? '' : 'btn-primary';
      },
      selectedInstanceModal(date){
        if(!this.monthDailyData[date]){
          return;
        }
        this.selectedDate = date;
        this.selectedInstance = this.monthDailyData[date];
        this.modifyInstanceModal.show();
      },
      isLargeScreen() {
        return this.mediaQuery.matches;
      },
      totalIncome(date){
        return this.monthDailyData[date]?.income.reduce((total, current) => total + current.amount, 0) ;
      },
      totalExpense(date){
        return this.monthDailyData[date]?.expense.reduce((total, current) => total + current.amount, 0) ;
      },
      getBalanceClass(date, type, balance) {
        return ((this.monthDailyData[date] || {[balance]: 0})[balance] < 0) ? 'expense' : (this.monthDailyData[date] || {[balance]: 0})[balance] > 0? `${type}-balance` : 'hide-dash';
      },
      updateMediaQuery(event) {
        this.mediaQuery = event.target;
      },
      async initializeData(){
          this.initialBalance = (await accountAPI.getUser()).user?.balance || 0;
          this.currentBalance = this.initialBalance;
          this.previousInitialBalance = this.initialBalance;
          this.monthDailyData = (await budgetTableAPI.getBudgetsInDateRange()).budgets || {};
          this.currMonth = moment(Object.keys(this.monthDailyData)[0]).month();
          this.currYear = moment(Object.keys(this.monthDailyData)[0]).year();
          this.calendar = this.getDaysInMonth(new Date (this.currYear , this.currMonth, 1), new Date (this.currYear , this.currMonth + 1, 0));
          await this.generate();
      },
      async generate() {
          let prevKey = Object.keys(this.monthDailyData)[0];
          for (let key of Object.keys(this.monthDailyData)) {
            const income = this.monthDailyData[key].income.reduce((total, current) => total + current.amount, 0);
            const expense = this.monthDailyData[key].expense.reduce((total, current) => total + current.amount, 0);
            this.currentBalance += income - expense;
            this.monthDailyData[key].previousBalance = this.monthDailyData[prevKey].currentBalance? this.monthDailyData[prevKey].currentBalance : this.initialBalance;
            this.monthDailyData[key].currentBalance = this.currentBalance;
            prevKey = key;
          }
      },
      async notesModal(date){
        this.selectedDate = date;
        let notes = await notesAPI.getByDate(date);
        if(notes.success){
          this.currentNotes = notes.notes;
        } else {
          this.currentNotes = {
            notes: ""
          };
        }
        this.noteModal.show();
      },
      async changeInitialBalance(){
        await accountAPI.updateUser({
          balance: this.initialBalance
        });
        this.currentBalance = this.initialBalance;
        this.monthlyBalances = {};
          for (let key of Object.keys(this.monthDailyData)) {
            const income = this.monthDailyData[key].income.reduce((total, current) => total + current.amount, 0);
            const expense = this.monthDailyData[key].expense.reduce((total, current) => total + current.amount, 0);
            this.currentBalance += income - expense;
            this.monthDailyData[key].currentBalance = this.currentBalance;
          }
      }
    },
    computed: {
      currentMonth () {
        if(this.currMonth > -1 && this.currYear > -1){
          this.getMonthlyData(this.currMonth, this.currYear);
        }
      },
      conditionalLayoutGrid() {
        return {
          'w-layout-grid': window.innerWidth > 600,
          'uui-table_row': true,
          'new-row': true
        }
      },
      isLargeScreen() {
        return this.mediaQuery.matches;
      },
      created() {
        this.mediaQuery.addEventListener("change", this.updateMediaQuery)
      },
      beforeDestroy() {
        this.mediaQuery.removeEventListener("change", this.updateMediaQuery)
      },
    },
    watch: {}
}
</script>
