// plan-wise-react-php/frontend/src/pages/BudgetTable.tsx
import React, { useEffect, useState, useLayoutEffect, useRef } from 'react';
import { Modal } from 'bootstrap';
import accountAPI from '../services/account-service';
import budgetTableAPI from '../services/budget-table-service';
import notesAPI from '../services/notes-service';
import NotesModal from '../components/NotesModal';
import ExpenseModal from '../components/ExpenseModal';
import IncomeModal from '../components/IncomeModal';
import ModifyInstanceModal from '../components/ModifyInstanceModal';
import moment from 'moment';
import './BudgetTable.css';

function BudgetTable() {
    const [currMonth, setCurrMonth] = useState(-1);
    const [currYear, setCurrYear] = useState(-1);
    const [initialBalance, setInitialBalance] = useState(0);
    const [monthDailyData, setMonthDailyData] = useState({});
    const [selectedDate, setSelectedDate] = useState(new Date().toISOString());
    const [balanceHistory, setBalanceHistory] = useState([]);
    const [months] = useState([
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December'
    ]);
    const [calendar, setCalendar] = useState([]);
    const [mediaQuery, setMediaQuery] = useState(window.matchMedia("(min-width: 724px)"));
    const [isLargeScreen, setIsLargeScreen] = useState(mediaQuery.matches);
    const [currentNotes, setCurrentNotes] = useState({
        notes: ""
    });

    const [selectedOptionCategoryHeader, setSelectedOptionCategoryHeader] = useState("");
    const [selectedClassCategoryHeader, setSelectedClassCategoryHeader] = useState("");
    const [selectedOptionHeader, setSelectedOptionHeader] = useState("");
    const [selectedClassHeader, setSelectedClassHeader] = useState("");
    const [selectedOption, setSelectedOption] = useState("");
    const [selectedClass, setSelectedClass] = useState("");
    const [headerExpense, setHeaderExpense] = useState("");
    const [headerSource, setHeaderSource] = useState("");
    const [headerAmount, setHeaderAmount] = useState(0);
    const [headerDate, setHeaderDate] = useState("");
    const [selectedInstance, setSelectedInstance] = useState({
        expense: [],
        income: []
    });

    const noteModalRef = useRef();
    const expenseModalRef = useRef();
    const incomeModalRef = useRef();
    const modifyInstanceModalRef = useRef();
    const [noteModal, setNoteModal] = useState(null);
    const [expenseModal, setExpenseModal] = useState(null);
    const [incomeModal, setIncomeModal] = useState(null);
    const [modifyInstanceModal, setModifyInstanceModal] = useState(null);
    
    const conditionalLayoutGrid = `${mediaQuery.matches? 'w-layout-grid' : ''} uui-table_row new-row`;

    useEffect(() => {
        document.title = "Plan Wise - Budget Table";
        initializeData();
    }, []);
    useEffect(() => {
        if (noteModalRef.current) {
            setNoteModal(new Modal(noteModalRef.current));
        }
    }, [noteModalRef.current]);
    useEffect(() => {
        if (expenseModalRef.current) {
            setExpenseModal(new Modal(expenseModalRef.current));
        }
    }, [expenseModalRef.current]);
    useEffect(() => {
        if (incomeModalRef.current) {
            setIncomeModal(new Modal(incomeModalRef.current));
        }
    }, [incomeModalRef.current]);
    useEffect(() => {
        if (modifyInstanceModalRef.current) {
            setModifyInstanceModal(new Modal(modifyInstanceModalRef.current));
        }
    }, [modifyInstanceModalRef.current]);

    const initializeData = async () => {
        const user = (await accountAPI.getUser()).user;
        setInitialBalance(user?.balance || 0);
        const monthDailyData = (await budgetTableAPI.getBudgetsInDateRange()).budgets || {};
        const currMonth = moment(Object.keys(monthDailyData)[0]).month();
        const currYear = moment(Object.keys(monthDailyData)[0]).year();
        setCurrMonth(currMonth);
        setCurrYear(currYear);
        const calendar = getDaysInMonth(new Date(currYear, currMonth, 1), new Date(currYear, currMonth + 1, 0));
        setCalendar(calendar);
        await generate(monthDailyData, user?.balance || 0);
    };
    
    const generate = async (monthDailyData, initialBalance) => {
        let prevKey = Object.keys(monthDailyData)[0];
        for (let key of Object.keys(monthDailyData)) {
            const income = monthDailyData[key].income.reduce((total, current) => total + current.amount, 0);
            const expense = monthDailyData[key].expense.reduce((total, current) => total + current.amount, 0);
            const currentBalance = (monthDailyData[prevKey].currentBalance || initialBalance) + income - expense;
            monthDailyData[key].previousBalance = monthDailyData[prevKey].currentBalance ? monthDailyData[prevKey].currentBalance : initialBalance;
            monthDailyData[key].currentBalance = currentBalance;
            prevKey = key;
        }
        setMonthDailyData(monthDailyData);
    };

    const getMonthlyData = async (month, year, initialBalance) => {
        console.log(initialBalance);
        setCurrMonth(month);
        setCurrYear(year);
        console.log(new Date(year, month, 1))
        const result = await budgetTableAPI.getBudgetsInDateRange(moment(new Date(year, month, 1)).format("YYYY-MM-DD"));
        const monthDailyData = result.budgets || {};
        setMonthDailyData(monthDailyData);
        let prevKey = Object.keys(monthDailyData)[0];
        for (let key of Object.keys(monthDailyData)) {
            const income = monthDailyData[key].income.reduce((total, current) => total + current.amount, 0);
            const expense = monthDailyData[key].expense.reduce((total, current) => total + current.amount, 0);
            const currentBalance = (monthDailyData[prevKey].currentBalance || initialBalance) + income - expense;
            monthDailyData[key].previousBalance = monthDailyData[prevKey].currentBalance ? monthDailyData[prevKey].currentBalance : initialBalance;
            monthDailyData[key].currentBalance = currentBalance;
            prevKey = key;
        }
        setMonthDailyData(monthDailyData);
        const calendar = getDaysInMonth(new Date(year, month, 1), new Date(year, month + 1, 0));
        setCalendar(calendar);
    };

    const incrementMonth = async () => {
        const monthData = Object.keys(monthDailyData);
        const newMonth = moment(monthData[0]).add(1, 'M').month();
        const newYear = moment(monthData[0]).add(1, 'M').year();
        setCurrMonth(newMonth);
        setCurrYear(newYear);
        balanceHistory.push(initialBalance);
        setBalanceHistory(balanceHistory);
        const calendar = getDaysInMonth(new Date(newYear, newMonth, 1), new Date(newYear, newMonth + 1, 0));
        setCalendar(calendar);
        const newInitialBalance = monthDailyData[monthData[monthData.length - 1]].currentBalance;
        setInitialBalance(newInitialBalance);
        const newCurrentBalance = newInitialBalance;
        setInitialBalance(newCurrentBalance);
        await getMonthlyData(newMonth, newYear, newInitialBalance);
        setCalendar(calendar);
    };

    const decrementMonth = async () => {
        const monthData = Object.keys(monthDailyData);
        const newMonth = moment(monthData[0]).subtract(1, 'M').month();
        const newYear = moment(monthData[0]).subtract(1, 'M').year();
        let newInitialBalance = 0;
        setCurrMonth(newMonth);
        setCurrYear(newYear);
        const calendar = getDaysInMonth(new Date(newYear, newMonth, 1), new Date(newYear, newMonth + 1, 0));
        setCalendar(calendar);
        if (balanceHistory.length > 0) {
            newInitialBalance = balanceHistory.pop();
            setInitialBalance(newInitialBalance);
        }
        setInitialBalance(newInitialBalance);
        setCalendar(calendar);
        await getMonthlyData(newMonth, newYear, newInitialBalance);
    };

    const getDaysInMonth = (start, end) => {
        const dates = [];
        let current = new Date(start);
        let index = 1;
        while (current <= end) {
            dates.push({
                date: moment(current).format('YYYY-MM-DD').toString(),
                dayOfWeek: current.getDay(),
                index: index
            });
            current.setDate(current.getDate() + 1);
            current = new Date(current);
            index++;
        }
        return dates;
    };

    const updateMediaQuery = (event) => {
        setMediaQuery(event.target);
        setIsLargeScreen(window.matchMedia("(min-width: 724px)").matches);
    };

    const changeInitialBalance = async () => {
        await accountAPI.updateUser({
            balance: initialBalance
        });
        await initializeData();
    }

    const addIncomeModal = async (date) => {
        setSelectedDate(date);
        setHeaderDate(date);
        setSelectedOptionHeader('Select Interval');
        setSelectedClassHeader('');
        setSelectedOption('Select Interval');
        setSelectedClass('');
        setHeaderSource('');
        setHeaderAmount(0);
        incomeModal.show();
    }

    const addExpenseModal = async (date) => {
        setSelectedDate(date);
        setHeaderDate(date);
        setSelectedOptionCategoryHeader({ category_name: 'Select Category' });
        setSelectedClassCategoryHeader('');
        setSelectedOptionHeader('Select Interval');
        setSelectedClassHeader('');
        setSelectedOption('Select Interval');
        setSelectedClass('');
        setHeaderExpense('');
        setHeaderAmount(0);
        expenseModal.show();
    }

    const selectedInstanceModal = async (date) => {
        setSelectedDate(date);
        setSelectedInstance(monthDailyData[date]);
        modifyInstanceModal.show();
    }

    const notesModal = async (date) => {
        try{
            let noteResponse = await notesAPI.getByDate(date);
            setCurrentNotes(noteResponse.notes || {
                notes: ""
            });
        } catch(e){
            setCurrentNotes({
                notes: ""
            });
        }
        setSelectedDate(date);
        noteModal.show();
    }

    const refreshTable = async () => {
        const month = moment(selectedDate).month();
        const year = moment(selectedDate).year();
        const calendar = getDaysInMonth(new Date(year, month, 1), new Date(year, month + 1, 0));
        setCalendar(calendar);
        const initBalance = monthDailyData[selectedDate].previousBalance;
        setInitialBalance(initBalance);
        await getMonthlyData(month, year, initBalance);
        setCalendar(calendar);
        expenseModal.hide();
        incomeModal.hide();
        modifyInstanceModal.hide();
    }

    useLayoutEffect(() => {
        mediaQuery.addEventListener("change", updateMediaQuery);
        return () => {
            mediaQuery.removeEventListener("change", updateMediaQuery);
        };
    }, [mediaQuery]);

    return (
    <section class="uui-section_table">
        <div class="uui-page-padding">
          <div class="uui-container-large">
            <div class="uui-padding-vertical-xhuge">
                <div class="uui-text-align-center">
                    <div class="uui-max-width-large align-center">
                    <h2 class="uui-heading-medium">Budget Table</h2>
                    <div class="uui-space-xsmall"></div>
                    <div class="uui-text-size-large">See where you&#x27;ll be if you stick to your budget<strong></strong></div>
                    </div>
                </div>
                    <div class="uui-table">
                        <div className="">
                            <div className={conditionalLayoutGrid}>
                                <div className="uui-table_row-content input-header">
                                    <span>Initial Balance:</span>
                                </div>
                                <div className="uui-table_row-content input-header">
                                    <input type="number" className="expense-input" value={initialBalance} onChange={e => setInitialBalance(e.target.value)} />
                                </div>
                                <div className="uui-table_row-content input-header">
                                    <button type="button" className="btn btn-primary" onClick={changeInitialBalance}>Change</button>
                                </div>
                            </div>
                            <div className="uui-table_heading-row">
                                <div className="uui-table_heading-row-text">Date</div>
                                <div className="uui-table_heading-row-text">Balance</div>
                                <div className="uui-table_heading-row-text">Income</div>
                                <div className="uui-table_heading-row-text">Expense</div>
                                <div className="uui-table_heading-row-text">Amount</div>
                                <div className="uui-table_heading-row-text">Action</div>
                            </div>
                            <div className="div-block">
                                <ul className="pagination">
                                    <li className="page-item">
                                        <a className="text-block-3 page-link-budget" href="#" onClick={decrementMonth}>{"<<"}</a>
                                    </li>
                                    <li>
                                        <div className="text-block-3 px-2">{months[currMonth]} {currYear < 0 ? '' : currYear}</div>
                                    </li>
                                    <li className="page-item">
                                        <a className="text-block-3 page-link-budget" href="#" onClick={incrementMonth}>{">>"}</a>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        {isLargeScreen && calendar.map((dayData, index) => (
                            <div key={index} className="w-layout-grid uui-table_row background-color-gray50">
                                <div className="w-layout-grid uui-table-row-day-of-month">
                                    <div className="div-block-2">
                                        <div className="uui-pricing07_row-lead-text date-column">{dayData.date}</div>
                                    </div>
                                </div>
                                {monthDailyData[dayData.date] && monthDailyData[dayData.date].previousBalance && monthDailyData[dayData.date].currentBalance ? (
                                    <div className="w-layout-grid uui-table-row-day-of-month balance-column">
                                        <div className="uui-text-size-medium starting-balance">
                                            {(monthDailyData[dayData.date].previousBalance || 0) > 0 ?
                                                `$${monthDailyData[dayData.date].previousBalance.toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}` :
                                                !isNaN(monthDailyData[dayData.date].previousBalance) ?
                                                    `-$${Math.abs(monthDailyData[dayData.date].previousBalance).toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : ''}
                                        </div>
                                        <div className="uui-text-size-medium ending-balance">
                                            {monthDailyData[dayData.date].currentBalance > 0 ?
                                                `$${monthDailyData[dayData.date].currentBalance.toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}` :
                                                `-$${Math.abs(monthDailyData[dayData.date].currentBalance).toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}`}
                                        </div>
                                    </div>
                                ) : (
                                    <div className="w-layout-grid uui-table-row-day-of-month">
                                        <div className="div-block-2"></div>
                                    </div>
                                )}

                                {monthDailyData[dayData.date] ? (
                                    <div className="w-layout-grid uui-table-row-day-of-month income-column">
                                        <div className={(monthDailyData[dayData.date].income || []).length > 0 ? 'uui-text-size-medium income' : 'uui-text-size-medium'}>
                                            {(monthDailyData[dayData.date].income || []).length > 0 ? `$${(monthDailyData[dayData.date].income || []).reduce((total, current) => total + current.amount, 0).toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : ''}
                                        </div>
                                        {Array(Math.max((monthDailyData[dayData.date].expense || []).length - 1, 0)).fill().map((_, i) => (
                                            <div key={i} className="uui-text-size-medium">
                                                <div>{i > (monthDailyData[dayData.date].income || []).length ? '' : ''}</div>
                                            </div>
                                        ))}
                                    </div>
                                ) : (
                                    <div className="w-layout-grid uui-table-row-day-of-month">
                                        <div className="div-block-2"></div>
                                    </div>
                                )}

                                {monthDailyData[dayData.date] ? (
                                    <div className="w-layout-grid uui-table-row-day-of-month expense-column">
                                        {(monthDailyData[dayData.date].expense || []).map((expense, index) => (
                                            <div key={index} className="uui-text-size-medium expense-cell">{expense.expenses}</div>
                                        ))}
                                    </div>
                                ) : (
                                    <div className="w-layout-grid uui-table-row-day-of-month">
                                        <div className="div-block-2"></div>
                                    </div>
                                )}

                                {monthDailyData[dayData.date] ? (
                                    <div className="w-layout-grid uui-table-row-day-of-month expense-price-column">
                                        {(monthDailyData[dayData.date].expense || []).map((expense, index) => (
                                            <div key={index} className="uui-text-size-medium expense-cell">
                                                $ {expense.amount.toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                                            </div>
                                        ))}
                                    </div>
                                ) : (
                                    <div className="w-layout-grid uui-table-row-day-of-month">
                                        <div className="div-block-2"></div>
                                    </div>
                                )}

                                <div className="w-layout-grid uui-table-row-day-of-month action-column">
                                    <div className="action">
                                        <div className="action-data">
                                            <button type="button" className="btn btn-primary" onClick={() => addIncomeModal(dayData.date)}>Add Income</button>
                                            <button type="button" className="btn btn-primary" onClick={() => addExpenseModal(dayData.date)}>Add Expense</button>
                                            <button type="button" className="btn btn-primary" disabled={!monthDailyData[dayData.date]} onClick={() => selectedInstanceModal(dayData.date)}>Modify Instance</button>
                                            <button type="button" className="btn btn-primary" onClick={() => notesModal(dayData.date)}>Notes</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        ))}

                        <div className="center-pagination">
                            <nav aria-label="Page navigation example">
                                <ul className="pagination">
                                    <li className="page-item">
                                        <a className="page-link" href="#" onClick={decrementMonth}>Previous</a>
                                    </li>
                                    <li className="page-item">
                                        <a className="page-link" href="#" onClick={incrementMonth}>Next</a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <NotesModal 
            ref={noteModalRef} 
            modalClosed={refreshTable} 
            currentNotes={currentNotes} 
            selectedDate={selectedDate} 
        />
        <ExpenseModal
            ref={expenseModalRef}
            onModalClosed={refreshTable}
            selectedOptionCategoryHeader={selectedOptionCategoryHeader}
            selectedClassCategoryHeader={selectedClassCategoryHeader}
            selectedOptionHeader={selectedOptionHeader}
            selectedClassHeader={selectedClassHeader}
            selectedOption={selectedOption}
            selectedClass={selectedClass}
            headerExpense={headerExpense}
            headerAmount={headerAmount}
            headerDate={headerDate}
            selectedDate={selectedDate}
        />
        <IncomeModal
            ref={incomeModalRef}
            onModalClosed={refreshTable}
            selectedOptionHeader={selectedOptionHeader}
            selectedClassHeader={selectedClassHeader}
            selectedOption={selectedOption}
            selectedClass={selectedClass}
            headerSource={headerSource}
            headerAmount={headerAmount}
            headerDate={headerDate}
            selectedDate={selectedDate}
        />
        <ModifyInstanceModal
            ref={modifyInstanceModalRef}
            onModalClosed={refreshTable}
            selectedDate={selectedDate}
            selectedInstance={selectedInstance}
        />
    </section>
  );
}

export default BudgetTable;

// plan-wise-angular-java/frontend/src/app/pages/budget-table/budget-table.component.ts
import { Component, OnInit, ViewChild, HostListener } from '@angular/core';
import { AccountService } from '../../../services/account.service';
import { BudgetTableService } from '../../../services/budget-table.service';
import { NoteService } from '../../../services/notes.service';
import { NotesModalComponent } from '../../components/notes-modal/notes-modal.component';
import { ExpenseModalComponent } from '../../components/expense-modal/expense-modal.component';
import { IncomeModalComponent } from '../../components/income-modal/income-modal.component';
import { ModifyInstanceModalComponent } from '../../components/modify-instance-modal/modify-instance-modal.component';
import * as moment from 'moment';

@Component({
  selector: 'app-budget-table',
  templateUrl: './budget-table.component.html',
  styleUrls: ['./budget-table.component.css', '../../../assets/components.css', '../../../assets/budgeting-app.css']
})
export class BudgetTableComponent implements OnInit {
  currMonth = -1;
  currYear = -1;
  initialBalance: any = 0;
  monthDailyData: any = {};
  selectedDate = new Date().toISOString();
  balanceHistory: any = [];
  months = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December'
  ];
  calendar: any = [];
  mediaQuery = window.matchMedia("(min-width: 724px)");
  isLargeScreen = this.mediaQuery.matches;
  currentNotes = {
    notes: ""
  };

  selectedOptionCategoryHeader: any = "";
  selectedClassCategoryHeader = "";
  selectedOptionHeader = "";
  selectedClassHeader = "";
  selectedOption = "";
  selectedClass = "";
  headerExpense = "";
  headerSource = "";
  headerAmount = 0;
  headerDate = "";
  selectedInstance = {
    expense: [],
    income: []
  };

  @ViewChild('noteModal') noteModal!: NotesModalComponent;
  @ViewChild('expenseModal') expenseModal!: ExpenseModalComponent;
  @ViewChild('incomeModal') incomeModal!: IncomeModalComponent;
  @ViewChild('modifyInstanceModal') modifyInstanceModal!: ModifyInstanceModalComponent;

  constructor(private accountAPI: AccountService, private budgetTableAPI: BudgetTableService, private notesAPI: NoteService) { }

  ngOnInit(): void {
    document.title = "Plan Wise - Budget Table";
    this.initializeData();
  }

  async initializeData() {
    const user: any = (await this.accountAPI.getUser());
    this.initialBalance = user?.balance || 0;
    const monthDailyData: any = (await this.budgetTableAPI.getBudgetsInDateRange(undefined));
    const currMonth = moment(Object.keys(monthDailyData.budgets)[0]).month();
    const currYear = moment(Object.keys(monthDailyData.budgets)[0]).year();
    this.currMonth = currMonth;
    this.currYear = currYear;
    const calendar = this.getDaysInMonth(new Date(currYear, currMonth, 1), new Date(currYear, currMonth + 1, 0));
    this.calendar = calendar;
    await this.generate(monthDailyData.budgets, user?.user.balance || 0);
  }

  async generate(monthDailyData: any, initialBalance: any) {
    let prevKey = Object.keys(monthDailyData)[0];
    for (let key of Object.keys(monthDailyData)) {
      const income = monthDailyData[key].income.reduce((total: any, current: any) => total + current.amount, 0);
      const expense = monthDailyData[key].expense.reduce((total: any, current: any) => total + current.amount, 0);
      const currentBalance = (monthDailyData[prevKey].currentBalance || initialBalance) + income - expense;
      monthDailyData[key].previousBalance = monthDailyData[prevKey].currentBalance ? monthDailyData[prevKey].currentBalance : initialBalance;
      monthDailyData[key].currentBalance = currentBalance;
      prevKey = key;
    }
    this.monthDailyData = monthDailyData;
  }

  async incrementMonth() {
    const monthData = Object.keys(this.monthDailyData);
    const newMonth = moment(monthData[0]).add(1, 'M').month();
    const newYear = moment(monthData[0]).add(1, 'M').year();
    this.currMonth = newMonth;
    this.currYear = newYear;
    this.balanceHistory.push(this.initialBalance);
    this.balanceHistory = this.balanceHistory;
    const calendar = this.getDaysInMonth(new Date(newYear, newMonth, 1), new Date(newYear, newMonth + 1, 0));
    this.calendar = calendar;
    const newInitialBalance = this.monthDailyData[monthData[monthData.length - 1]].currentBalance;
    this.initialBalance = newInitialBalance;
    const newCurrentBalance = newInitialBalance;
    this.initialBalance = newCurrentBalance;
    await this.getMonthlyData(newMonth, newYear, newInitialBalance);
    this.calendar = calendar;
  }
  

  async decrementMonth() {
    const monthData = Object.keys(this.monthDailyData);
    const newMonth = moment(monthData[0]).subtract(1, 'M').month();
    const newYear = moment(monthData[0]).subtract(1, 'M').year();
    let newInitialBalance: any = 0;
    this.currMonth = newMonth;
    this.currYear = newYear;
    const calendar = this.getDaysInMonth(new Date(newYear, newMonth, 1), new Date(newYear, newMonth + 1, 0));
    this.calendar = calendar;
    if (this.balanceHistory.length > 0) {
      newInitialBalance = this.balanceHistory.pop();
      this.initialBalance = newInitialBalance;
    }
    this.initialBalance = newInitialBalance;
    this.calendar = calendar;
    await this.getMonthlyData(newMonth, newYear, newInitialBalance);
  }
  
  getDaysInMonth(start: any, end: any) {
    const dates = [];
    let current = new Date(start);
    let index = 1;
    while (current <= end) {
      dates.push({
        date: moment(current).format('YYYY-MM-DD').toString(),
        dayOfWeek: current.getDay(),
        index: index
      });
      current.setDate(current.getDate() + 1);
      current = new Date(current);
      index++;
    }
    return dates;
  }
  
  async changeInitialBalance() {
    await this.accountAPI.updateUser({
      balance: this.initialBalance
    });
    await this.initializeData();
  }
  
  addIncomeModal(date: any) {
    this.selectedDate = date;
    this.headerDate = date;
    this.selectedOptionHeader = 'Select Interval';
    this.selectedClassHeader = '';
    this.selectedOption = 'Select Interval';
    this.selectedClass = '';
    this.headerSource = '';
    this.headerAmount = 0;
    this.incomeModal.open();
  }
  
  addExpenseModal(date: any) {
    this.selectedDate = date;
    this.headerDate = date;
    this.selectedOptionCategoryHeader = { category_name: 'Select Category' };
    this.selectedClassCategoryHeader = '';
    this.selectedOptionHeader = 'Select Interval';
    this.selectedClassHeader = '';
    this.selectedOption = 'Select Interval';
    this.selectedClass = '';
    this.headerExpense = '';
    this.headerAmount = 0;
    this.expenseModal.open();
  }
  
  selectedInstanceModal(date: any) {
    this.selectedDate = date;
    this.selectedInstance = this.monthDailyData[date];
    this.modifyInstanceModal.open();
  }
  
  async notesModal(date: any) {
    try {
      let noteResponse: any = await this.notesAPI.getByDate(date);
      this.currentNotes = noteResponse.notes[0] || {
        notes: ""
      };
      this.selectedDate = date;
      this.noteModal.open(this.currentNotes, this.selectedDate);
    } catch(e) {
      this.currentNotes = {
        notes: ""
      };
      this.selectedDate = date;
      this.noteModal.open(this.currentNotes, this.selectedDate);
    }
  }
  
  async refreshTable() {
    const month = moment(this.selectedDate).month();
    const year = moment(this.selectedDate).year();
    const calendar = this.getDaysInMonth(new Date(year, month, 1), new Date(year, month + 1, 0));
    this.calendar = calendar;
    const initBalance = this.monthDailyData[this.selectedDate].previousBalance;
    this.initialBalance = initBalance;
    await this.getMonthlyData(month, year, initBalance);
    this.calendar = calendar;
    this.expenseModal.close();
    this.incomeModal.close();
    this.modifyInstanceModal.close();
  }
  async getMonthlyData(month: any, year: any, initialBalance: any) {
    console.log(initialBalance);
    this.currMonth = month;
    this.currYear = year;
    console.log(new Date(year, month, 1));
    const result: any = await this.budgetTableAPI.getBudgetsInDateRange(moment(new Date(year, month, 1)).format("YYYY-MM-DD"));
    const monthDailyData = result.budgets || {};
    this.monthDailyData = monthDailyData;
    let prevKey = Object.keys(monthDailyData)[0];
    for (let key of Object.keys(monthDailyData)) {
      const income = monthDailyData[key].income.reduce((total: any, current: any) => total + current.amount, 0);
      const expense = monthDailyData[key].expense.reduce((total: any, current: any) => total + current.amount, 0);
      const currentBalance = (monthDailyData[prevKey].currentBalance || initialBalance) + income - expense;
      monthDailyData[key].previousBalance = monthDailyData[prevKey].currentBalance ? monthDailyData[prevKey].currentBalance : initialBalance;
      monthDailyData[key].currentBalance = currentBalance;
      prevKey = key;
    }
    this.monthDailyData = monthDailyData;
    const calendar = this.getDaysInMonth(new Date(year, month, 1), new Date(year, month + 1, 0));
    this.calendar = calendar;
  }
  
  @HostListener('window:resize', ['$event'])
  onResize(event: any) {
    this.updateMediaQuery(event);
  }
  
  updateMediaQuery(event: any) {
    this.mediaQuery = event.target;
    this.isLargeScreen = window.matchMedia("(min-width: 724px)").matches;
  }

  getBalanceDisplay(balance: number): string {
    if (balance > 0) {
      return `$${balance.toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
    } else if (!isNaN(balance)) {
      return `-$${Math.abs(balance).toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
    } else {
      return '';
    }
  }

  getIncomeDisplay(income: any[]): string {
    if (income.length > 0) {
      const totalIncome = income.reduce((total, current) => total + current.amount, 0);
      return `$${totalIncome.toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
    } else {
      return '';
    }
  }

  getArray(length: number): any[] {
    return Array(length);
  }

}

<section class="uui-section_table">
    <div class="uui-page-padding">
      <div class="uui-container-large">
        <div class="uui-padding-vertical-xhuge">
            <div class="uui-text-align-center">
                <div class="uui-max-width-large align-center">
                <h2 class="uui-heading-medium">Budget Table</h2>
                <div class="uui-space-xsmall"></div>
                <div class="uui-text-size-large">See where you&#x27;ll be if you stick to your budget<strong></strong></div>
                </div>
            </div>
                <div class="uui-table">
                    <div class="">
                        <div [ngClass]="{'w-layout-grid': isLargeScreen, 'uui-table_row': true, 'new-row': true}">
                            <div class="uui-table_row-content input-header">
                              <span>Initial Balance:</span>
                            </div>
                            <div class="uui-table_row-content input-header">
                              <input type="number" class="expense-input" [(ngModel)]="initialBalance" />
                            </div>
                            <div class="uui-table_row-content input-header">
                              <button type="button" class="btn btn-primary" (click)="changeInitialBalance()">Change</button>
                            </div>
                        </div>                          
                        <div class="uui-table_heading-row">
                          <div class="uui-table_heading-row-text">Date</div>
                          <div class="uui-table_heading-row-text">Balance</div>
                          <div class="uui-table_heading-row-text">Income</div>
                          <div class="uui-table_heading-row-text">Expense</div>
                          <div class="uui-table_heading-row-text">Amount</div>
                          <div class="uui-table_heading-row-text">Action</div>
                        </div>
                        <div class="div-block">
                          <ul class="pagination">
                            <li class="page-item">
                              <a class="text-block-3 page-link-budget" href="javascript:void(0)" (click)="decrementMonth()"><<</a>
                            </li>
                            <li>
                              <div class="text-block-3 px-2">{{months[currMonth]}} {{currYear < 0 ? '' : currYear}}</div>
                            </li>
                            <li class="page-item">
                              <a class="text-block-3 page-link-budget" href="javascript:void(0)" (click)="incrementMonth()">>></a>
                            </li>
                          </ul>
                        </div>
                    </div>
                      
                    <div *ngIf="isLargeScreen">
                        <div *ngFor="let dayData of calendar; index as i" class="w-layout-grid uui-table_row background-color-gray50">
                            <div class="w-layout-grid uui-table-row-day-of-month">
                                <div class="div-block-2">
                                <div class="uui-pricing07_row-lead-text date-column">{{dayData.date}}</div>
                                </div>
                            </div>

                            <div *ngIf="monthDailyData[dayData.date] && monthDailyData[dayData.date].previousBalance && monthDailyData[dayData.date].currentBalance" class="w-layout-grid uui-table-row-day-of-month balance-column">
                                <div class="uui-text-size-medium starting-balance">
                                {{ getBalanceDisplay(monthDailyData[dayData.date].previousBalance || 0) }}
                                </div>
                                <div class="uui-text-size-medium ending-balance">
                                {{ getBalanceDisplay(monthDailyData[dayData.date].currentBalance) }}
                                </div>
                            </div>
                            <div *ngIf="!monthDailyData[dayData.date] || !monthDailyData[dayData.date].previousBalance || !monthDailyData[dayData.date].currentBalance" class="w-layout-grid uui-table-row-day-of-month">
                                <div class="div-block-2"></div>
                            </div>
                            <div *ngIf="monthDailyData[dayData.date]" class="w-layout-grid uui-table-row-day-of-month income-column">
                                <div class="{{(monthDailyData[dayData.date].income || []).length > 0 ? 'uui-text-size-medium income' : 'uui-text-size-medium'}}">
                                {{ getIncomeDisplay(monthDailyData[dayData.date].income || []) }}
                                </div>
                                <div *ngFor="let _ of getArray((monthDailyData[dayData.date].expense || []).length - 1)" class="uui-text-size-medium">
                                    <div></div>
                                </div>                                  
                            </div>
                            <div *ngIf="!monthDailyData[dayData.date]" class="w-layout-grid uui-table-row-day-of-month">
                                <div class="div-block-2"></div>
                            </div>
                            <div *ngIf="monthDailyData[dayData.date]" class="w-layout-grid uui-table-row-day-of-month expense-column">
                                <div *ngFor="let expense of (monthDailyData[dayData.date].expense || [])" class="uui-text-size-medium expense-cell">{{expense.expenses}}</div>
                            </div>
                            <div *ngIf="!monthDailyData[dayData.date]" class="w-layout-grid uui-table-row-day-of-month">
                                <div class="div-block-2"></div>
                            </div>
                            <div *ngIf="monthDailyData[dayData.date]" class="w-layout-grid uui-table-row-day-of-month expense-price-column">
                                <div *ngFor="let expense of (monthDailyData[dayData.date].expense || [])" class="uui-text-size-medium expense-cell">
                                $ {{expense.amount.toLocaleString('en-US', { style: 'decimal', minimumFractionDigits: 2, maximumFractionDigits: 2 })}}
                                </div>
                            </div>
                            <div *ngIf="!monthDailyData[dayData.date]" class="w-layout-grid uui-table-row-day-of-month">
                                <div class="div-block-2"></div>
                            </div>

                            <div class="w-layout-grid uui-table-row-day-of-month action-column">
                                <div class="action">
                                <div class="action-data">
                                    <button type="button" class="btn btn-primary" (click)="addIncomeModal(dayData.date)">Add Income</button>
                                    <button type="button" class="btn btn-primary" (click)="addExpenseModal(dayData.date)">Add Expense</button>
                                    <button type="button" class="btn btn-primary" [disabled]="!monthDailyData[dayData.date]" (click)="selectedInstanceModal(dayData.date)">Modify Instance</button>
                                    <button type="button" class="btn btn-primary" (click)="notesModal(dayData.date)">Notes</button>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                      
                    <div class="center-pagination">
                        <nav aria-label="Page navigation example">
                          <ul class="pagination">
                            <li class="page-item">
                              <a class="page-link" href="javascript:void(0)" (click)="decrementMonth()">Previous</a>
                            </li>
                            <li class="page-item">
                              <a class="page-link" href="javascript:void(0)" (click)="incrementMonth()">Next</a>
                            </li>
                          </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <app-notes-modal 
        #noteModal 
        (modalClosed)="refreshTable()" 
        [currentNotes]="currentNotes" 
        [selectedDate]="selectedDate">
    </app-notes-modal>
    <app-expense-modal
        #expenseModal
        (modalClosed)="refreshTable()"
        [selectedOptionCategoryHeader]="selectedOptionCategoryHeader"
        [selectedClassCategoryHeader]="selectedClassCategoryHeader"
        [selectedOptionHeader]="selectedOptionHeader"
        [selectedClassHeader]="selectedClassHeader"
        [headerExpense]="headerExpense"
        [headerAmount]="headerAmount"
        [headerDate]="headerDate"
        [selectedDate]="selectedDate">
    </app-expense-modal>
    <app-income-modal
        #incomeModal
        (modalClosed)="refreshTable()"
        [selectedOptionHeader]="selectedOptionHeader"
        [selectedClassHeader]="selectedClassHeader"
        [headerSource]="headerSource"
        [headerAmount]="headerAmount"
        [headerDate]="headerDate"
        [selectedDate]="selectedDate">
    </app-income-modal>
    <app-modify-instance-modal
        #modifyInstanceModal
        (modalClosed)="refreshTable()"
        [selectedDate]="selectedDate"
        [selectedInstance]="selectedInstance">
    </app-modify-instance-modal>
</section>
