// plan-wise-angular-java/frontend/src/app/components/expense-modal/expense-modal.component.ts
import { Component, Input, OnInit, ViewChild, ElementRef } from '@angular/core';
import * as bootstrap from 'bootstrap';
import { CategoryService } from '../../../services/category.service';
import { ExpenseService } from '../../../services/expense.service';

@Component({
  selector: 'app-expense-modal',
  templateUrl: './expense-modal.component.html',
  styleUrls: ['./expense-modal.component.css']
})
export class ExpenseModalComponent implements OnInit {
  @Input() headerExpense: string = '';
  @Input() headerAmount: number = -1;
  @Input() selectedDate: string = '';
  @Input() selectedClassHeader: string = '';
  @Input() selectedOptionHeader: string = '';
  @Input() selectedClassCategoryHeader: string = '';
  @Input() selectedOptionCategoryHeader: string = '';
  @Input() onModalClosed: any;
  @ViewChild('expenseModal') expenseModal!: ElementRef;
  localHeaderExpense: string = '';
  localHeaderAmount: number = -1;
  localSelectedDate: string = '';
  localSelectedClassHeader: string = '';
  localSelectedOptionHeader: string = '';
  localSelectedClassCategoryHeader: string = '';
  localSelectedOptionCategoryHeader: any = '';
  options = [
    { text: 'Daily', class: 'daily' },
    { text: 'Weekly', class: 'weekly' },
    { text: 'Every Other Week', class: 'every-other-week' },
    { text: 'Monthly', class: 'monthly' },
    { text: 'Quarterly', class: 'quarterly' },
    { text: 'Every 6 Months', class: 'every-6-months' },
    { text: 'Annually', class: 'annually' },
    { text: 'One Time', class: 'one-time-expense' }];
  categories = [];
  modalInstance: any;

  constructor(private categoryService: CategoryService, private expenseService: ExpenseService) { }

  ngOnInit(): void {
    this.categoryService.getAll().then((response: any) => {
      this.categories = response.category || [];
    });
    this.onShow();
  }

  onShow(): void {
    this.localHeaderExpense = this.headerExpense;
    this.localHeaderAmount = this.headerAmount;
    this.localSelectedDate = new Date(this.selectedDate).toISOString().substring(0, 10);
    this.localSelectedClassHeader = this.selectedClassHeader;
    this.localSelectedOptionHeader = this.selectedOptionHeader;
    this.localSelectedClassCategoryHeader = this.selectedClassCategoryHeader;
    this.localSelectedOptionCategoryHeader = this.selectedOptionCategoryHeader;
  }

  selectOptionHeader(option: any): void {
    this.localSelectedOptionHeader = option.text;
    this.localSelectedClassHeader = option.class;
  }

  selectCategoryHeader(category: any): void {
    this.localSelectedOptionCategoryHeader = category;
    this.localSelectedClassCategoryHeader = category.category_name === 'Select Category' ? '' : 'btn-primary';
  }

  async createExpense(): Promise<void> {
    try {
      let body = {
        expenses: this.localHeaderExpense,
        amount: this.localHeaderAmount,
        start_date: this.localSelectedDate,
        frequency: this.options.findIndex(x => this.localSelectedClassHeader === x.class),
        category: this.localSelectedOptionCategoryHeader.id
      };
      console.log(body);
      let response: any = await this.expenseService.create(body);
      if (response.success) {
        this.onModalClosed();
      } else {
        console.error(response.message);
      }
    } catch (exception) {
      console.error(exception);
    }
  }

  open() {
    this.modalInstance = new bootstrap.Modal(this.expenseModal.nativeElement);
    this.modalInstance.show();
  }

  close() {
    this.modalInstance.hide();
  }
}

<div #expenseModal class="modal fade" id="expenseModal" tabindex="-1" role="dialog" aria-labelledby="expenseModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="expenseModalLabel">New Expense</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="income-expense-input">
                    <div class="income-expense-row">
                        <span>Expense: </span>
                        <input type="text" class="expense-input modal-input" [(ngModel)]="localHeaderExpense" />
                    </div>
                    <div class="income-expense-row">
                        <span>Amount($): </span>
                        <input type="number" class="expense-input modal-input" [(ngModel)]="localHeaderAmount" />
                    </div>
                    <div class="income-expense-row">
                        <span>Date: </span>
                        <input type="date" pattern="\d{4}-\d{2}-\d{2}" disabled="true" class="expense-input modal-input" [(ngModel)]="localSelectedDate" />
                    </div>
                    <div class="income-expense-row">
                        <span>Frequency: </span>
                        <div class="dropdown dropdown-border modal-input" data-bs-toggle="dropdown" data-bs-display="static">
                            <button class="btn dropdown-toggle" [ngClass]="localSelectedClassHeader" type="button" id="dropdownMenuButtonHeader" aria-expanded="false">
                                {{localSelectedOptionHeader}}
                            </button>
                            <span class="dropdown-icon">▼</span>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButtonHeader">
                                <li class="mt-1">
                                    <a class="dropdown-item" href="javascript:void(0)" (click)="selectOptionHeader({ text: '', class: '' })">Select Interval</a>
                                </li>
                                <li *ngFor="let option of options" class="mt-1">
                                    <a class="dropdown-item" [ngClass]="option.class" href="javascript:void(0)" (click)="selectOptionHeader(option)">{{option.text}}</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="income-expense-row">
                        <span>Category: </span>
                        <div class="dropdown dropdown-border  modal-input" data-bs-toggle="dropdown" data-bs-display="static">
                            <button class="btn dropdown-toggle" [ngClass]="localSelectedClassCategoryHeader" type="button" id="dropdownCategoryButtonHeader" aria-expanded="false">
                                {{localSelectedOptionCategoryHeader?.category_name || "Select Category"}}
                            </button>
                            <span class="dropdown-icon">▼</span>
                            <ul class="dropdown-menu" aria-labelledby="selectCategoryHeader">
                                <li class="mt-1">
                                    <a class="dropdown-item" href="javascript:void(0)" (click)="selectCategoryHeader({ category_name: 'Select Category' })">Select Category</a>
                                </li>
                                <li *ngFor="let category of categories">
                                    <a class="one-time-expense dropdown-item" href="javascript:void(0)" (click)="selectCategoryHeader(category)">{{category.category_name}}</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" (click)="createExpense()">Save changes</button>
            </div>
        </div>
    </div>
</div>

// plan-wise-react-php/frontend/src/components/ExpenseModal.tsx
import React, { useState, useEffect, forwardRef } from "react";
import categoryAPI from '../services/category-service';
import expenseAPI from '../services/expense-service';
import './ExpenseModal.css'

const ExpenseModal = forwardRef((props, ref) => {
    const [localHeaderExpense, setLocalHeaderExpense] = useState("");
    const [localHeaderAmount, setLocalHeaderAmount] = useState(0);
    const [localSelectedDate, setLocalSelectedDate] = useState(props.selectedDate);
    const [localSelectedClassHeader, setLocalSelectedClassHeader] = useState("");
    const [localSelectedOptionHeader, setLocalSelectedOptionHeader] = useState("");
    const [localSelectedClassCategoryHeader, setLocalSelectedClassCategoryHeader] = useState("");
    const [localSelectedOptionCategoryHeader, setLocalSelectedOptionCategoryHeader] = useState("");
    const [options] = useState([
        { text: 'Daily', class: 'daily' },
        { text: 'Weekly', class: 'weekly' },
        { text: 'Every Other Week', class: 'every-other-week' },
        { text: 'Monthly', class: 'monthly' },
        { text: 'Quarterly', class: 'quarterly' },
        { text: 'Every 6 Months', class: 'every-6-months' },
        { text: 'Annually', class: 'annually' },
        { text: 'One Time', class: 'one-time-expense' }
    ]);
    const [categories, setCategories] = useState([]);

    useEffect(() => {
        categoryAPI.getAll().then(response => {
        setCategories(response.category || []);
        });
        onShow();
    }, []);
    useEffect(() => {
        const observer = new MutationObserver((mutationsList) => {
            for(let mutation of mutationsList) {
                if (mutation.type === 'attributes' && mutation.attributeName === 'class') {
                    if(ref.current.className.includes("show")){
                        onShow();
                    }
                }
            }
        });
    
        observer.observe(ref.current, { attributes: true });
    
        return () => {
            observer.disconnect();
        };
    }, [
        props.headerExpense, 
        props.headerAmount, 
        props.selectedDate, 
        props.selectedClassHeader, 
        props.selectedOptionHeader, 
        props.selectedClassCategoryHeader, 
        props.selectedOptionCategoryHeader
    ]);

    const onShow = () => {
        setLocalHeaderExpense(props.headerExpense);
        setLocalHeaderAmount(props.headerAmount);
        setLocalSelectedDate((new Date(props.selectedDate)).toISOString().substring(0, 10));
        setLocalSelectedClassHeader(props.selectedClassHeader);
        setLocalSelectedOptionHeader(props.selectedOptionHeader);
        setLocalSelectedClassCategoryHeader(props.selectedClassCategoryHeader);
        setLocalSelectedOptionCategoryHeader(props.selectedOptionCategoryHeader);
    };

    const selectOptionHeader = (option) => {
        setLocalSelectedOptionHeader(option.text);
        setLocalSelectedClassHeader(option.class);
    };

    const selectCategoryHeader = (category) => {
        setLocalSelectedOptionCategoryHeader(category);
        setLocalSelectedClassCategoryHeader(category.category_name === 'Select Category' ? '' : 'btn-primary');
    };

    const createExpense = async () => {
        try {
        let body = {
            expenses: localHeaderExpense,
            amount: localHeaderAmount,
            start_date: localSelectedDate,
            frequency: options.findIndex(x => localSelectedClassHeader === x.class),
            category: localSelectedOptionCategoryHeader.id
        };
        console.log(body)
        let response = await expenseAPI.create(body);
        if (response.success) {
            props.onModalClosed();
        } else {
            console.error(response.message);
        }
        } catch (exception) {
        console.error(exception);
        }
    };

    return (
        <div ref={ref} className="modal fade" id="expenseModal" tabIndex="-1" role="dialog" aria-labelledby="expenseModalLabel" aria-hidden="true">
        <div className="modal-dialog" role="document">
            <div className="modal-content">
            <div className="modal-header">
                <h5 className="modal-title" id="expenseModalLabel">New Expense</h5>
                <button type="button" className="close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div className="modal-body">
                <div className="income-expense-input">
                <div className="income-expense-row">
                    <span>Expense: </span>
                    <input type="text" className="expense-input modal-input" value={localHeaderExpense} onChange={e => setLocalHeaderExpense(e.target.value)} />
                </div>
                <div className="income-expense-row">
                    <span>Amount($): </span>
                    <input type="number" className="expense-input modal-input" value={localHeaderAmount} onChange={e => setLocalHeaderAmount(e.target.value)} />
                </div>
                <div className="income-expense-row">
                    <span>Date: </span>
                    <input type="date" pattern="\d{4}-\d{2}-\d{2}" disabled={true} className="expense-input modal-input" value={localSelectedDate} onChange={e => setLocalSelectedDate(e.target.value)} />
                </div>
                <div className="income-expense-row">
                    <span>Frequency: </span>
                    <div className="dropdown dropdown-border modal-input" data-bs-toggle="dropdown" data-bs-display="static">
                    <button className={`btn dropdown-toggle ${localSelectedClassHeader}`} type="button" id="dropdownMenuButtonHeader" aria-expanded="false">
                        {localSelectedOptionHeader}
                    </button>
                    <span className="dropdown-icon">▼</span>
                    <ul className="dropdown-menu" aria-labelledby="dropdownMenuButtonHeader">
                        <li className="mt-1">
                        <a className="dropdown-item" href="#" onClick={() => selectOptionHeader({ text: '', class: '' })}>Select Interval</a>
                        </li>
                        {options.map(option => (
                        <li key={option.text} className="mt-1">
                            <a className={`${option.class} dropdown-item`} href="#" onClick={() => selectOptionHeader(option)}>{option.text}</a>
                        </li>
                        ))}
                    </ul>
                    </div>
                </div>
                <div className="income-expense-row">
                    <span>Category: </span>
                    <div className="dropdown dropdown-border  modal-input" data-bs-toggle="dropdown" data-bs-display="static">
                    <button className={`btn dropdown-toggle ${localSelectedClassCategoryHeader}`} type="button" id="dropdownCategoryButtonHeader" aria-expanded="false">
                        {localSelectedOptionCategoryHeader?.category_name || "Select Category"}
                    </button>
                    <span className="dropdown-icon">▼</span>
                    <ul className="dropdown-menu" aria-labelledby="selectCategoryHeader">
                        <li className="mt-1">
                        <a className="dropdown-item" href="#" onClick={() => selectCategoryHeader({ category_name: 'Select Category' })}>Select Category</a>
                        </li>
                        {
                            categories.map(category => (
                                <li key={category.id}>
                                    <a className="one-time-expense dropdown-item" href="#" onClick={() => selectCategoryHeader(category)}>{category.category_name}</a>
                                </li>
                            ))
                        }
                    </ul>
                    </div>
                </div>
                </div>
            </div>
            <div className="modal-footer">
                <button type="button" className="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" className="btn btn-primary" onClick={createExpense}>Save changes</button>
            </div>
            </div>
        </div>
        </div>
    );
});

export default ExpenseModal;
