// plan-wise-angular-java/frontend/src/app/components/modify-instance-modal/modify-instance-modal.component.ts
import { Component, Input, OnInit, SimpleChanges, ViewChild, ElementRef } from '@angular/core';
import * as bootstrap from 'bootstrap';
import { BudgetTableService } from '../../../services/budget-table.service';

@Component({
  selector: 'app-modify-instance-modal',
  templateUrl: './modify-instance-modal.component.html',
  styleUrls: ['./modify-instance-modal.component.css', '../../../assets/components.css', '../../../assets/budgeting-app.css']
})
export class ModifyInstanceModalComponent implements OnInit {

  @Input() selectedInstance: any;
  @Input() onModalClosed: any;
  @Input() selectedDate!: string;
  @ViewChild('modifyInstanceModal') modifyInstanceModal!: ElementRef;

  expenseInstanceIndex = 0;
  incomeInstanceIndex = 0;
  localSelectedInstance: any = { income: [], expense: [] };
  localSelectedDate = '';
  modalInstance: any;
  activeTab = 'expense';

  constructor(private budgetTableService: BudgetTableService) { }

  ngOnInit() {
    this.onShow();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['selectedInstance'] || changes['selectedDate']) {
      this.onShow();
    }
  }

  onShow() {
    this.expenseInstanceIndex = 0;
    this.incomeInstanceIndex = 0;
    this.localSelectedDate = this.selectedDate;
    this.localSelectedInstance = this.selectedInstance;
    console.log(this.selectedInstance.expense);
  }

  open() {
    this.modalInstance = new bootstrap.Modal(this.modifyInstanceModal.nativeElement);
    this.modalInstance.show();
  }

  close() {
    this.modalInstance.hide();
  }

  handleExpenseChange(e: any) {
    let newExpense: any = [...this.localSelectedInstance.expense];
    newExpense[this.expenseInstanceIndex].expenses = e.target.value;
    this.localSelectedInstance = { ...this.localSelectedInstance, expense: newExpense };
  }

  handleAmountChange(e: any) {
    let newExpense: any = [...this.localSelectedInstance.expense];
    newExpense[this.expenseInstanceIndex].amount = e.target.value;
    this.localSelectedInstance = { ...this.localSelectedInstance, expense: newExpense };
  }

  handleSourceChange(e: any) {
    let newIncome: any = [...this.localSelectedInstance.income];
    newIncome[this.incomeInstanceIndex].source = e.target.value;
    this.localSelectedInstance = { ...this.localSelectedInstance, income: newIncome };
  }

  handleIncomeAmountChange(e: any) {
    let newIncome: any = [...this.localSelectedInstance.income];
    newIncome[this.incomeInstanceIndex].amount = e.target.value;
    this.localSelectedInstance = { ...this.localSelectedInstance, income: newIncome };
  }

  handleDateChange(e: any) {
    this.localSelectedDate = e.target.value;
  }

  incrementExpenseInstanceIndex() {
    if (this.expenseInstanceIndex === this.localSelectedInstance.expense.length - 1) {
      return;
    }
    this.expenseInstanceIndex += 1;
  }

  decrementExpenseInstanceIndex() {
    if (this.expenseInstanceIndex === 0) {
      return;
    }
    this.expenseInstanceIndex -= 1;
  }

  incrementIncomeInstanceIndex() {
    if (this.incomeInstanceIndex === this.localSelectedInstance.income.length - 1) {
      return;
    }
    this.incomeInstanceIndex += 1;
  }

  decrementIncomeInstanceIndex() {
    if (this.incomeInstanceIndex === 0) {
      return;
    }
    this.incomeInstanceIndex -= 1;
  }

  async modifyInstance () {
      try {
          let body = {
              date: this.localSelectedDate,
              income: this.localSelectedInstance.income,
              expense: this.localSelectedInstance.expense
          };
          let response: any = await this.budgetTableService.updateBudgets(body);
          if (response.success) {
              this.onModalClosed();
          } else {
              console.error(response.message);
          }
      } catch (exception) {
          console.error(exception);
      }
  };
  
  switchTab(tab: string) {
    this.activeTab = tab;
  }
}

<div #modifyInstanceModal class="modal fade" id="modifyInstanceModal" tabindex="-1" role="dialog" aria-labelledby="modifyInstanceModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modifyInstanceModalLabel">Modify Instance</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <ul class="nav nav-tabs" id="instanceTabs" role="tablist">
                    <li class="nav-item" role="presentation" *ngIf="localSelectedInstance.expense.length > 0">
                      <button class="nav-link" [class.active]="activeTab === 'expense'" id="expense-data-tab" type="button" role="tab" aria-controls="expense-data" aria-selected="true" (click)="switchTab('expense')">Expense</button>
                    </li>
                    <li class="nav-item" role="presentation" *ngIf="localSelectedInstance.income.length > 0">
                      <button class="nav-link" [class.active]="activeTab === 'income'" id="income-data-tab" type="button" role="tab" aria-controls="income-data" aria-selected="false" (click)="switchTab('income')">Income</button>
                    </li>
                </ul>
                <div class="tab-content" id="instanceTabsContent">
                    <div class="tab-pane fade" [class.show]="activeTab === 'expense'" [class.active]="activeTab === 'expense'" id="expense-data" role="tabpanel" aria-labelledby="expense-data-tab" *ngIf="localSelectedInstance.expense.length > 0">
                        <div class="income-expense-input">
                            <div class="income-expense-row">
                                <span>Expense: </span>
                                <input type="text" class="expense-input modal-input" [(ngModel)]="localSelectedInstance.expense[expenseInstanceIndex].expenses" />
                            </div>
                            <div class="income-expense-row">
                                <span>Amount($): </span>
                                <input type="number" class="expense-input modal-input" [(ngModel)]="localSelectedInstance.expense[expenseInstanceIndex].amount" />
                            </div>
                            <div class="income-expense-row">
                                <span>Date: </span>
                                <input type="date" pattern="\d{4}-\d{2}-\d{2}" disabled="true" class="expense-input modal-input" [(ngModel)]="localSelectedDate" />
                            </div>
                        </div>
                        <div class="center-pagination">
                            <nav aria-label="Page navigation example">
                                <ul class="pagination">
                                <li class="page-item">
                                    <a class="page-link" (click)="decrementExpenseInstanceIndex()"><< Previous</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" (click)="incrementExpenseInstanceIndex()">Next >></a>
                                </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="tab-pane fade" [class.show]="activeTab === 'income'" [class.active]="activeTab === 'income'" id="income-data" role="tabpanel" aria-labelledby="income-data-tab" *ngIf="localSelectedInstance.income.length > 0">
                        <div class="income-expense-input">
                            <div class="income-expense-row">
                                <span>Source: </span>
                                <input type="text" class="expense-input modal-input" [(ngModel)]="localSelectedInstance.income[incomeInstanceIndex].source" />
                            </div>
                            <div class="income-expense-row">
                                <span>Amount($): </span>
                                <input type="number" class="expense-input modal-input" [(ngModel)]="localSelectedInstance.income[incomeInstanceIndex].amount" />
                            </div>
                            <div class="income-expense-row">
                                <span>Date: </span>
                                <input type="date" pattern="\d{4}-\d{2}-\d{2}" disabled="true" class="expense-input modal-input" [(ngModel)]="localSelectedDate" />
                            </div>
                        </div>
                            <div class="center-pagination">
                            <nav aria-label="Page navigation example">
                                <ul class="pagination">
                                <li class="page-item">
                                    <a class="page-link" (click)="decrementIncomeInstanceIndex()"><< Previous</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" (click)="incrementIncomeInstanceIndex()">Next >></a>
                                </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="close()">Close</button>
                <button type="button" class="btn btn-primary" (click)="modifyInstance()">Save changes</button>
            </div>
        </div>
    </div>
</div>

// plan-wise-react-php/frontend/src/components/ModifyInstanceModal.tsx
import React, { useState, useEffect, forwardRef } from 'react';
import budgetTableAPI from '../services/budget-table-service';
import './ModifyInstanceModal.css';

const ModifyInstanceModal = forwardRef((props: any, ref: any) => {
    const [expenseInstanceIndex, setExpenseInstanceIndex] = useState<any>(0);
    const [incomeInstanceIndex, setIncomeInstanceIndex] = useState<any>(0);
    const [localSelectedInstance, setLocalSelectedInstance] = useState<any>({ income: [], expense: [] });
    const [localSelectedDate, setLocalSelectedDate] = useState<any>('');
  
    useEffect(() => {
        onShow();
    }, []);
    useEffect(() => {
        const observer = new MutationObserver((mutationsList: any) => {
            for (let mutation of mutationsList) {
                if (mutation.type === 'attributes' && mutation.attributeName === 'class') {
                    if (ref.current.className.includes("show")) {
                        onShow();
                    }
                }
            }
        });
    
        observer.observe(ref.current, { attributes: true });
    
        return () => {
            observer.disconnect();
        };
    }, [
        props.selectedInstance, 
        props.selectedDate, 
    ]);

    const onShow = () => {
        setExpenseInstanceIndex(0);
        setIncomeInstanceIndex(0);
        setLocalSelectedDate(props.selectedDate);
        setLocalSelectedInstance(props.selectedInstance);
        console.log(props.selectedInstance.expense);
    };
    const handleExpenseChange = (e: any) => {
        let newExpense = [...localSelectedInstance.expense];
        newExpense[expenseInstanceIndex].expenses = e.target.value;
        setLocalSelectedInstance({ ...localSelectedInstance, expense: newExpense });
    };
        
    const handleAmountChange = (e: any) => {
        let newExpense = [...localSelectedInstance.expense];
        newExpense[expenseInstanceIndex].amount = e.target.value;
        setLocalSelectedInstance({ ...localSelectedInstance, expense: newExpense });
    };
    
    const handleSourceChange = (e: any) => {
        let newIncome = [...localSelectedInstance.income];
        newIncome[incomeInstanceIndex].source = e.target.value;
        setLocalSelectedInstance({ ...localSelectedInstance, income: newIncome });
    };
    
    const handleIncomeAmountChange = (e: any) => {
        let newIncome = [...localSelectedInstance.income];
        newIncome[incomeInstanceIndex].amount = e.target.value;
        setLocalSelectedInstance({ ...localSelectedInstance, income: newIncome });
    };
    
    const handleDateChange = (e: any) => {
        setLocalSelectedDate(e.target.value);
    };
    
    const incrementExpenseInstanceIndex = () => {
        if (expenseInstanceIndex === localSelectedInstance.expense.length - 1) {
            return;
        }
        setExpenseInstanceIndex(expenseInstanceIndex + 1);
    };

    const decrementExpenseInstanceIndex = () => {
        if (expenseInstanceIndex === 0) {
            return;
        }
        setExpenseInstanceIndex(expenseInstanceIndex - 1);
    };

    const incrementIncomeInstanceIndex = () => {
        if (incomeInstanceIndex === localSelectedInstance.income.length - 1) {
            return;
        }
        setIncomeInstanceIndex(incomeInstanceIndex + 1);
    };

    const decrementIncomeInstanceIndex = () => {
        if (incomeInstanceIndex === 0) {
            return;
        }
        setIncomeInstanceIndex(incomeInstanceIndex - 1);
    };

    const modifyInstance = async () => {
        try {
            let body = {
                date: localSelectedDate,
                income: localSelectedInstance.income,
                expense: localSelectedInstance.expense
            };
            let response = await budgetTableAPI.updateBudgets(body);
            if (response.success) {
                props.onModalClosed();
            } else {
                console.error(response.message);
            }
        } catch (exception: any) {
            console.error(exception);
        }
    };
    return (
        <div className="modal fade" id="modifyInstanceModal" ref={ref} tabIndex={-1} role="dialog" aria-labelledby="modifyInstanceModalLabel" aria-hidden="true">
            <div className="modal-dialog" role="document">
                <div className="modal-content">
                    <div className="modal-header">
                        <h5 className="modal-title" id="modifyInstanceModalLabel">Modify Instance</h5>
                        <button type="button" className="close" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div className="modal-body">
                        <ul className="nav nav-tabs" id="instanceTabs" role="tablist">
                            {localSelectedInstance.expense.length > 0 && (
                                <li className="nav-item" role="presentation">
                                    <button className="nav-link active" id="expense-data-tab" data-bs-toggle="tab" data-bs-target="#expense-data" type="button" role="tab" aria-controls="expense-data" aria-selected="true">Expense</button>
                                </li>
                            )}
                            {localSelectedInstance.income.length > 0 && (
                                <li className="nav-item" role="presentation">
                                    <button className="nav-link" id="income-data-tab" data-bs-toggle="tab" data-bs-target="#income-data" type="button" role="tab" aria-controls="income-data" aria-selected="false">Income</button>
                                </li>
                            )}
                        </ul>
                        <div className="tab-content" id="instanceTabsContent">
                            {localSelectedInstance.expense.length > 0 && (
                                <div className="tab-pane fade show active" id="expense-data" role="tabpanel" aria-labelledby="expense-data-tab">
                                    <div className="income-expense-input">
                                        <div className="income-expense-row">
                                            <span>Expense: </span>
                                            <input type="text" className="expense-input modal-input" value={localSelectedInstance.expense[expenseInstanceIndex].expenses} onChange={handleExpenseChange} />
                                        </div>
                                        <div className="income-expense-row">
                                            <span>Amount($): </span>
                                            <input type="number" className="expense-input modal-input" value={localSelectedInstance.expense[expenseInstanceIndex].amount} onChange={handleAmountChange} />
                                        </div>
                                        <div className="income-expense-row">
                                            <span>Date: </span>
                                            <input type="date" pattern="\d{4}-\d{2}-\d{2}" disabled={true} className="expense-input modal-input" value={localSelectedDate} onChange={handleDateChange} />
                                        </div>
                                    </div>
                                    <div className="center-pagination">
                                        <nav aria-label="Page navigation example">
                                            <ul className="pagination">
                                                <li className="page-item">
                                                    <a className="page-link" onClick={decrementExpenseInstanceIndex}>&lt;&lt; Previous</a>
                                                </li>
                                                <li className="page-item">
                                                    <a className="page-link" onClick={incrementExpenseInstanceIndex}>Next &gt;&gt;</a>
                                                </li>
                                            </ul>
                                        </nav>
                                    </div>
                                </div>
                            )}
                            {localSelectedInstance.income.length > 0 && (
                                <div className="tab-pane fade" id="income-data" role="tabpanel" aria-labelledby="income-data-tab">
                                    <div className="income-expense-input">
                                        <div className="income-expense-row">
                                            <span>Source: </span>
                                            <input type="text" className="expense-input modal-input" value={localSelectedInstance.income[incomeInstanceIndex].source} onChange={handleSourceChange} />
                                        </div>
                                        <div className="income-expense-row">
                                            <span>Amount($): </span>
                                            <input type="number" className="expense-input modal-input" value={localSelectedInstance.income[incomeInstanceIndex].amount} onChange={handleIncomeAmountChange} />
                                        </div>
                                        <div className="income-expense-row">
                                            <span>Date: </span>
                                            <input type="date" pattern="\d{4}-\d{2}-\d{2}" disabled={true} className="expense-input modal-input" value={localSelectedDate} onChange={handleDateChange} />
                                        </div>
                                    </div>
                                    <div className="center-pagination">
                                        <nav aria-label="Page navigation example">
                                            <ul className="pagination">
                                                <li className="page-item">
                                                    <a className="page-link" onClick={decrementIncomeInstanceIndex}>&lt;&lt; Previous</a>
                                                </li>
                                                <li className="page-item">
                                                    <a className="page-link" onClick={incrementIncomeInstanceIndex}>Next &gt;&gt;</a>
                                                </li>
                                            </ul>
                                        </nav>
                                    </div>
                                </div>
                            )}
                        </div>
                    </div>
                    <div className="modal-footer">
                        <button type="button" className="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" className="btn btn-primary" onClick={modifyInstance}>Save changes</button>
                    </div>
                </div>
            </div>
        </div>
    );
});

export default ModifyInstanceModal;
