// plan-wise-angular-java/frontend/src/app/components/notes-modal/notes-modal.component.ts
import { Component, Input, OnInit, ViewChild, ElementRef  } from '@angular/core';
import * as bootstrap from 'bootstrap';
import { NoteService } from '../../../services/notes.service';

@Component({
  selector: 'app-notes-modal',
  templateUrl: './notes-modal.component.html',
  styleUrls: ['./notes-modal.component.css', '../../../assets/components.css', '../../../assets/budgeting-app.css']
})
export class NotesModalComponent {

  @Input() currentNotes: any;
  @Input() selectedDate: string = '';
  @ViewChild('notesModal') notesModal!: ElementRef;
  localCurrentNotes: any;
  localSelectedDate: string = '';
  modalInstance: any;

  constructor(private notesService: NoteService) { }

  ngOnInit(): void {
    this.localCurrentNotes = this.currentNotes;
    this.localSelectedDate = this.selectedDate;
  }

  open() {
    this.modalInstance = new bootstrap.Modal(this.notesModal.nativeElement);
    this.modalInstance.show();
  }

  close() {
    this.modalInstance.hide();
  }

  async saveNotes(date: string): Promise<void> {
    if (!this.currentNotes.id) {
      await this.notesService.create({
        date: date,
        notes: this.localCurrentNotes.notes
      });
    } else {
      await this.notesService.updateByDate(date, this.localCurrentNotes);
    }
  }
}

<div #notesModal class="modal fade" id="notesModal" tabIndex="-1" aria-labelledby="notesModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="notesModalLabel">Notes</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <label htmlFor="notesTextArea" class="form-label">{{localSelectedDate}}</label>
                <textarea class="form-control" id="notesTextArea" rows="3" [(ngModel)]="localCurrentNotes.notes"></textarea>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" (click)="saveNotes(localSelectedDate)">Save changes</button>
            </div>
        </div>
    </div>
</div>

// plan-wise-react-php/frontend/src/components/NotesModal.tsx
import React, { useState, useEffect, forwardRef, useImperativeHandle } from 'react';
import { Modal } from 'bootstrap';
import notesAPI from '../services/notes-service';
import './Header.css'

const NotesModal = forwardRef((props: any, ref: any) => {
    const [localCurrentNotes, setLocalCurrentNotes] = useState(props.currentNotes);
    const [localSelectedDate, setLocalSelectedDate] = useState(props.selectedDate);

    useEffect(() => {
        onShow();
    }, [props.currentNotes, props.selectedDate]);

    const onShow = () => {
        setLocalSelectedDate(props.selectedDate);
        setLocalCurrentNotes(props.currentNotes);
    };
    
    const saveNotes = async (date: Date) => {
        if(!props.currentNotes.id){
            await notesAPI.create({
                date: date,
                notes: localCurrentNotes.notes
            });
        } else{
            await notesAPI.updateByDate(date, localCurrentNotes)
        }
    }

    return (
        <div ref={ref} className="modal fade" id="notesModal" tabIndex={-1} aria-labelledby="notesModalLabel" aria-hidden="true">
            <div className="modal-dialog">
                <div className="modal-content">
                    <div className="modal-header">
                        <h5 className="modal-title" id="notesModalLabel">Notes</h5>
                        <button type="button" className="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div className="modal-body">
                        <label htmlFor="notesTextArea" className="form-label">{localSelectedDate}</label>
                        <textarea className="form-control" id="notesTextArea" rows={3} value={localCurrentNotes.notes} onChange={e => setLocalCurrentNotes({ ...localCurrentNotes, notes: e.target.value })}></textarea>
                    </div>
                    <div className="modal-footer">
                        <button type="button" className="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" className="btn btn-primary" data-bs-dismiss="modal" onClick={() => {saveNotes(localSelectedDate)}}>Save changes</button>
                    </div>
                </div>
            </div>
        </div>
    );
});

export default NotesModal;
